{
 "title": "StackState - Spotlight",
 "tags": [
  "stackstate",
  "spotlight"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(kube_service_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Anomalies detected (per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(low_anomalies_found_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "LOW"
    },
    {
     "expr": "sum(increase(low_anomalies_found_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "MEDIUM"
    },
    {
     "expr": "sum(increase(low_anomalies_found_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "HIGH"
    }
   ]
  },
  {
   "title": "Errors (per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(processing_error_count_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "Processing"
    },
    {
     "expr": "sum(increase(invalid_data_count_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "Invalid Data"
    },
    {
     "expr": "sum(increase(dead_on_arrival_count_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "Training"
    }
   ]
  },
  {
   "title": "Job runs (per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(train_pipeline_runs_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "train"
    },
    {
     "expr": "sum(increase(detect_pipeline_runs_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m])) by (service)",
     "legendFormat": "detect"
    }
   ]
  },
  {
   "title": "Should the AAD scale? (number of streams)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spotlight_streams_with_anomaly_check{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) by (service)",
     "legendFormat": "Anomaly Health Checks"
    },
    {
     "expr": "sum(spotlight_streams_checked{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) by (service)",
     "legendFormat": "Checked Streams"
    }
   ]
  },
  {
   "title": "Training runs (quantiles)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90000000000000002, sum(rate(train_timings_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(train_timings_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(train_timings_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Detect runs (quantiles)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90000000000000002, sum(rate(detect_timings_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(detect_timings_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(detect_timings_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    }
   ]
  }
 ]
}