{
 "title": "StackState - Correlation workers",
 "tags": [
  "stackstate",
  "correlate"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(kube_service_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Correlate - Approximate count of elements produced",
   "type": "graph",
   "description": "Amount of elements produced in the correlator",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_correlate_unique_active_element_approx_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Correlate - Approximate count of created elements in the last hour",
   "type": "graph",
   "description": "Approximate count of new elements create in the past hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_correlate_element_create_approx_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Correlator buffers occupancy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_correlate_buffer_occupancy{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{correlation_type}}"
    }
   ]
  }
 ]
}