
{{- define "stackstate.backup.stackgraph.container.init" }}
name: wait
command:
  - sh
  - -c
  - |
    /entrypoint -c {{ include "stackstate.s3proxy.endpoint" . }},{{ include "stackgraph.hbase.waitfor" . }},{{ template "common.fullname.short" . }}-{{- if include "suse-observability.features.enabled" (dict "key" "server.split" "context" .) }}initializer:1618{{ else }}server-headless:7070{{ end }} -t 300
image: "{{include "stackstate.wait.image.registry" .}}/{{ .Values.global.wait.image.repository }}:{{ .Values.global.wait.image.tag }}"
imagePullPolicy: Always
{{- end }}
{{- define "stackstate.backup.stackgraph.container.main" }}
{{- $imageTagConfig := dict "ImageTag" .Values.stackstate.components.server.image.tag }}
name: backup-stackgraph
image: "{{ include "stackstate.image.registry" . }}/{{ .Values.stackstate.components.server.image.repository }}{{ .Values.stackstate.components.all.image.repositorySuffix }}:{{ include "stackstate.server.image.tag" (merge $imageTagConfig .) }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.server.image.pullPolicy | quote }}
command:
  - '/backup-restore-scripts/backup-stackgraph.sh'
env:
  {{- include "stackstate.backup.envvars" . | nindent 2 }}
  {{- include "stackstate.baseurls.envvars" .  | nindent 2 }}
  - name: PROMETHEUS_WRITE_ENDPOINT
    value: http://{{ include "stackstate.vmagent.endpoint" . }}:8429/api/v1/write
  - name: HADOOP_USER_NAME
    value: nobody
  - name: ZOOKEEPER_QUORUM
    value: {{ include "stackgraph.zookeeper.endpoint" . | quote }}
  {{- include "stackstate.component.envsFromExistingSecrets" .Values.stackstate.components.all.envsFromExistingSecrets }}
{{- with .Values.stackstate.components.backup.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
volumeMounts:
  {{- include "stackstate.backup.volumeMounts" . | nindent 2 }}
  - name: tmp-data
    mountPath: /tmp-data
{{- end }}

{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "stackstate.backup.stackgraph.container.main" .) -}}
{{- $stackgraphBackupMainContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideInitContainer := fromYaml (include "stackstate.backup.stackgraph.container.init" .) -}}
{{- $stackgraphBackupInitContainer := (merge $overrideInitContainer $commonContainer) -}}
{{- if eq (include "stackstate.backup.stackGraph.enabled" .) "true" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "stackstate.backup.stackgraph.fullname" . }}
  labels:
    app.kubernetes.io/name: suse-observability
    app.kubernetes.io/component: backup-sg
    {{- include "suse-observability.labels.global" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.backup.stackGraph.scheduled.schedule | quote }}
  suspend: {{ eq .Values.backup.stackGraph.scheduled.implementation "v2" }}
  {{- if .Values.deployment.compatibleWithArgoCD }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: backup
        {{- include "suse-observability.labels.global" . | nindent 8 }}
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: {{ include "stackstate.job.ttlSecondsAfterFinished" . }}
      template:
        metadata:
          {{- include "stackstate.backup.podAnnotations" . | nindent 10 }}
          {{- include "stackstate.backup.podLabels" . | nindent 10 }}
        spec:
          initContainers:
          - {{- toYaml $stackgraphBackupInitContainer | nindent 12 }}
          containers:
          - {{- toYaml $stackgraphBackupMainContainer | nindent 12 }}
          {{- include "stackstate.image.pullSecret.name" (dict "context" $) | nindent 10 }}
          volumes:
            {{- include "stackstate.backup.volumes" . | nindent 12 }}
            - name: tmp-data
              persistentVolumeClaim:
                claimName: {{ template "common.fullname.short" . }}-backup-stackgraph-tmp-data
          {{- include "stackstate.backup.nodeSelector" . | nindent 10 }}
          {{- include "stackstate.backup.affinity" . | nindent 10 }}
          {{- include "stackstate.backup.tolerations" . | nindent 10 }}
        {{- if .Values.backup.stackGraph.securityContext.enabled }}
          securityContext: {{- omit .Values.backup.stackGraph.securityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
          restartPolicy: Never
---
{{ end }}

{{- define "stackstate.backup.stackgraph.v2.container.init" }}
name: wait
command:
  - sh
  - -c
  - |
    /entrypoint -c {{ include "stackstate.s3proxy.endpoint" . }},{{ include "stackgraph.hbase.waitfor" . }},{{ template "common.fullname.short" . }}-{{- if include "suse-observability.features.enabled" (dict "key" "server.split" "context" .) }}initializer:1618{{ else }}server-headless:7070{{ end }} -t 300
image: "{{include "stackstate.wait.image.registry" .}}/{{ .Values.global.wait.image.repository }}:{{ .Values.global.wait.image.tag }}"
imagePullPolicy: Always
{{- end }}
{{- define "stackstate.backup.stackgraph.v2.container.main" }}
{{- $imageTagConfig := dict "ImageTag" .Values.stackstate.components.server.image.tag }}
{{- $serverServiceConfig := dict "ServiceName" "server" "ServiceConfig"  .Values.stackstate.components.server }}
name: backup-stackgraph-v2
image: "{{ include "stackstate.image.registry" (merge (dict) $serverServiceConfig .) }}/{{ .Values.stackstate.components.server.image.repository }}{{ .Values.stackstate.components.all.image.repositorySuffix }}:{{ include "stackstate.server.image.tag" (merge (dict) $imageTagConfig .) }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.server.image.pullPolicy | quote }}
command:
  - '/backup-restore-scripts/backup-stackgraph-v2.sh'
env:
  {{- include "stackstate.backup.envvars" . | nindent 2 }}
  {{- include "stackstate.baseurls.envvars" .  | nindent 2 }}
  - name: PROMETHEUS_WRITE_ENDPOINT
    value: http://{{ include "stackstate.vmagent.endpoint" . }}:8429/api/v1/write
  - name: HADOOP_USER_NAME
    value: nobody
  - name: ZOOKEEPER_QUORUM
    value: {{ include "stackgraph.zookeeper.endpoint" . | quote }}
  {{- include "stackstate.component.envsFromExistingSecrets" .Values.stackstate.components.all.envsFromExistingSecrets }}
{{- with .Values.stackstate.components.backup.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
volumeMounts:
  {{- include "stackstate.backup.volumeMounts" . | nindent 2 }}
  - name: tmp-data
    mountPath: /tmp-data
{{- end }}

{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "stackstate.backup.stackgraph.v2.container.main" .) -}}
{{- $stackgraphBackupV2MainContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideInitContainer := fromYaml (include "stackstate.backup.stackgraph.v2.container.init" .) -}}
{{- $stackgraphBackupV2InitContainer := (merge $overrideInitContainer $commonContainer) -}}
{{ if .Values.global.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "common.fullname.short" . }}-backup-sg-v2
  labels:
    app.kubernetes.io/name: suse-observability
    app.kubernetes.io/component: backup-sg-v2
    {{- include "suse-observability.labels.global" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.backup.stackGraph.scheduled.schedule | quote }}
  suspend: {{ eq .Values.backup.stackGraph.scheduled.implementation "v1" }}
  {{- if .Values.deployment.compatibleWithArgoCD }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: backup-v2
        {{- include "suse-observability.labels.global" . | nindent 8 }}
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: {{ include "stackstate.job.ttlSecondsAfterFinished" . }}
      template:
        metadata:
          {{- include "stackstate.backup.podAnnotations" . | nindent 10 }}
          {{- include "stackstate.backup.podLabels" (merge (dict "BackupComponent" "backup-v2") .) | nindent 10 }}
        spec:
          initContainers:
          - {{- toYaml $stackgraphBackupV2InitContainer | nindent 12 }}
          containers:
          - {{- toYaml $stackgraphBackupV2MainContainer | nindent 12 }}
          {{- include "stackstate.image.pullSecret.name" (dict "context" $) | nindent 10 }}
          volumes:
            {{- include "stackstate.backup.volumes" . | nindent 12 }}
            - name: tmp-data
              persistentVolumeClaim:
                claimName: {{ template "common.fullname.short" . }}-backup-stackgraph-v2-tmp-data
          {{- include "stackstate.backup.nodeSelector" . | nindent 10 }}
          {{- include "stackstate.backup.affinity" . | nindent 10 }}
          {{- include "stackstate.backup.tolerations" . | nindent 10 }}
        {{- if .Values.backup.stackGraph.securityContext.enabled }}
          securityContext: {{- omit .Values.backup.stackGraph.securityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
          restartPolicy: Never
---
{{- end }}

{{- define "stackstate.backup.configuration.container.init" }}
name: wait
command:
  - sh
  - -c
  - |
    /entrypoint -c {{ include "stackstate.s3proxy.endpoint" . }},{{ include "stackgraph.hbase.waitfor" . }},{{ template "common.fullname.short" . }}-{{- if include "suse-observability.features.enabled" (dict "key" "server.split" "context" .) }}initializer:1618{{ else }}server-headless:7070{{ end }} -t 300
image: "{{include "stackstate.wait.image.registry" .}}/{{ .Values.global.wait.image.repository }}:{{ .Values.global.wait.image.tag }}"
imagePullPolicy: Always
{{- end }}
{{- define "stackstate.backup.configuration.container.main" }}
{{- $imageTagConfig := dict "ImageTag" .Values.stackstate.components.server.image.tag }}
name: backup-settings
image: "{{ include "stackstate.image.registry" . }}/{{ .Values.stackstate.components.server.image.repository }}{{ .Values.stackstate.components.all.image.repositorySuffix }}:{{ include "stackstate.server.image.tag" (merge $imageTagConfig .) }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.server.image.pullPolicy | quote }}
command:
  - '/backup-restore-scripts/backup-configuration.sh'
envFrom:
  - secretRef:
      name: {{ include "stackstate.secret.name.license" .  }}
env:
  {{- include "stackstate.backup.envvars" . | nindent 2 }}
  {{- include "stackstate.baseurls.envvars" .  | nindent 2 }}
  {{ if .Values.backup.configuration.yaml.maxSizeLimit }}
  - name: CONFIG_FORCE_stackstate_yaml_codePointLimit
    value: "{{ include "stackstate.backup.yaml.maxSizeLimit" . }}"
  {{ end }}
  - name: PROMETHEUS_WRITE_ENDPOINT
    value: http://{{ include "stackstate.vmagent.endpoint" . }}:8429/api/v1/write
  - name: HADOOP_USER_NAME
    value: nobody
  - name: ZOOKEEPER_QUORUM
    value: {{ include "stackgraph.zookeeper.endpoint" . | quote }}
  {{- include "stackstate.component.envsFromExistingSecrets" .Values.stackstate.components.all.envsFromExistingSecrets }}
{{- with .Values.stackstate.components.configurationBackup.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
volumeMounts:
  {{- include "stackstate.backup.volumeMounts" . | nindent 2 }}
{{- end }}

{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "stackstate.backup.configuration.container.main" .) -}}
{{- $configBackupMainContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideInitContainer := fromYaml (include "stackstate.backup.configuration.container.init" .) -}}
{{- $configBackupInitContainer := (merge $overrideInitContainer $commonContainer) }}
{{- $settingsContext := merge (dict "BackupSettings" "configurationBackup") . }}
{{- if eq (include "stackstate.backup.configuration.enabled" .) "true" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "common.fullname.short" . }}-backup-conf
  labels:
    app.kubernetes.io/name: suse-observability
    app.kubernetes.io/component: backup-settings
    {{- include "suse-observability.labels.global" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.backup.configuration.scheduled.schedule | quote }}
  {{- if .Values.deployment.compatibleWithArgoCD }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: backup
        {{- include "suse-observability.labels.global" . | nindent 8 }}
    spec:
      backoffLimit: 1
      {{- if not .Values.deployment.compatibleWithArgoCD }}
      ttlSecondsAfterFinished: {{ include "stackstate.job.ttlSecondsAfterFinished" . }}
      {{- end }}
      template:
        metadata:
          {{- include "stackstate.backup.podAnnotations" $settingsContext | nindent 10 }}
          {{- include "stackstate.backup.podLabels" $settingsContext | nindent 10 }}
        spec:
          initContainers:
          - {{- toYaml $configBackupInitContainer | nindent 12 }}
          containers:
          - {{- toYaml $configBackupMainContainer | nindent 12 }}
          {{- include "stackstate.image.pullSecret.name" (dict "context" $) | nindent 10 }}
          # Specifically setting this to empty string to unset previously used service account https://github.com/helm/helm/issues/10183
          serviceAccount: ""
          serviceAccountName: ""
          volumes:
            {{- include "stackstate.backup.volumes" . | nindent 12 }}
          {{- include "stackstate.backup.nodeSelector" $settingsContext | nindent 10 }}
          {{- include "stackstate.backup.affinity" $settingsContext | nindent 10 }}
          {{- include "stackstate.backup.tolerations" $settingsContext | nindent 10 }}
        {{- if .Values.backup.configuration.securityContext.enabled }}
          securityContext: {{- omit .Values.backup.configuration.securityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
          restartPolicy: Never
{{- end }}
