{{/*
PVC and Job are kept around to keep old settings backups available, they should be removed after several releases (i.e. Q3 2026 or later)
*/}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $settingsContext := merge (dict "BackupSettings" "configurationBackup") . }}
apiVersion: batch/v1
kind: Job
metadata:
  {{- if .Values.deployment.compatibleWithArgoCD }}
  generateName: init-pvc-
  {{- else }}
  name: {{ template "common.fullname.short" . }}-init-pvc-{{ now | date "02t150405" }}
  {{- end }}
  labels:
    app.kubernetes.io/component: backup-settings-init
    {{- include "suse-observability.labels.global" . | nindent 4 }}
  annotations:
    {{- if .Values.deployment.compatibleWithArgoCD }}
    argocd.argoproj.io/hook: Sync
    {{- end }}
  {{- with .Values.backup.initJobAnnotations }}
    {{- toYaml . | nindent 4}}
  {{- end }}
spec:
  ttlSecondsAfterFinished: {{ include "stackstate.job.ttlSecondsAfterFinished" . }}
  template:
    metadata:
      {{- include "stackstate.backup.podAnnotations" $settingsContext | nindent 6 }}
      {{- include "stackstate.backup.podLabels" $settingsContext | nindent 6 }}
    spec:
      containers:
        - name: init
          image: "{{include "stackstate.containerTools.image.registry" .}}/{{ .Values.stackstate.components.containerTools.image.repository }}:{{ .Values.stackstate.components.containerTools.image.tag }}"
          imagePullPolicy: {{ .Values.stackstate.components.containerTools.image.pullPolicy | quote }}
          command:
            - "echo"
            - "Init settings backup pvc"
          securityContext:
            {{- $commonContainer.securityContext | toYaml | nindent 12 }}
          resources:
            limits:
              cpu: 10m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
          volumeMounts:
            - name: settings-backup-data
              mountPath: /settings-backup-data

    {{- include "stackstate.image.pullSecret.name" (dict "images" (list .Values.stackstate.components.all.image) "context" $) | nindent 6 }}
      restartPolicy: Never
      {{- include "stackstate.backup.nodeSelector" $settingsContext | nindent 6 }}
      {{- include "stackstate.backup.affinity" $settingsContext | nindent 6 }}
      {{- include "stackstate.backup.tolerations" $settingsContext | nindent 6 }}
{{- if .Values.backup.configuration.securityContext.enabled }}
      securityContext: {{- omit .Values.backup.configuration.securityContext "enabled" | toYaml | nindent 8 }}
{{- end }}
      volumes:
      - name: settings-backup-data
        persistentVolumeClaim:
          claimName: {{ template "common.fullname.short" . }}-settings-backup-data
