{
 "title": "Tenant sizing estimation",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(stackstate_check_change_total, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current number of components and relations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (__name__) (stackstate_sync_extTopo_changes_total)"
    }
   ]
  },
  {
   "title": "Maximum number of components and relations in the past month",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time (count by (__name__) (stackstate_sync_extTopo_changes_total)[30d:1h])"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Quota",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{ namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{ namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{ namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{ namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{ namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{ namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_cache{cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_swap{cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}) by (pod)"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Persistent storage",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_used_bytes {job=\"kubelet\",metrics_path=\"/metrics\",namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=~\"$namespace\"} ) by (persistentvolumeclaim)"
      },
      {
       "expr": "sum(kubelet_volume_stats_capacity_bytes{job=\"kubelet\",metrics_path=\"/metrics\",namespace=~\"$namespace\"} ) by (persistentvolumeclaim)"
      }
     ]
    },
    {
     "title": "Ephemeral storage",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_ephemeral_storage_used_bytes{exported_namespace=\"$namespace\"}) by (exported_pod)"
      }
     ]
    }
   ]
  },
  { "title": "Data intake", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Receiver - Created elements hourly total",
   "type": "graph",
   "description": "Total elements created",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_element_create_passed_count{namespace=\"$namespace\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Receiver - Incoming created elements in the last hour (approximate) count",
   "type": "graph",
   "description": "Amount of created in the past hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_element_create_request_approx_count{namespace=\"$namespace\"}",
     "legendFormat": "{{element_type}}"
    },
    {
     "expr": "stackstate_receiver_element_create_passed_max{namespace=\"$namespace\"}",
     "legendFormat": "{{element_type}} budget"
    }
   ]
  },
  {
   "title": "Receiver - Current incoming element (approximate) count",
   "type": "graph",
   "description": "Amount of data being offered to the receiver at this moment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_unique_element_request_approx_count{namespace=\"$namespace\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Number of connected agents",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (namespace)(stackstate_receiver_unique_element_passed_count{element_type=\"agent\",namespace=\"$namespace\"})"
    }
   ]
  }
 ]
}