apiVersion: v1
appVersion: 0.0.1
version: 0.1.0
description: "Create o11y-tenants manifests"
home: https://github.com/stackvista/helm-charts-internal
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: SUSE Observability team
    email: suse-observability-ops@suse.com
name: tenantprovisioning
