{
 "title": "StackState - HDFS - DataNodes",
 "tags": [
  "hdfs",
  "stackstate"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Blocks Written / Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blocks Written",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_datanode_blockswritten{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "Blocks Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_datanode_blocksread{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  { "title": "Fsync Time / Num Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Fsync Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_datanode_fsyncnanosavgtime{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Fsync Num Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_datanode_fsyncnanosnumops{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  { "title": "Data Packets Blocked / Num Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Data Packet Blocked Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_datanode_senddatapacketblockedonnetworknanosavgtime{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Data Packet Blocked Num Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_datanode_senddatapacketblockedonnetworknanosnumops{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "Packet Transfer Blocked / Num Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packet Transfer Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "dfs.datanode.SendDataPacketTransferNanosAvgTime",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Packet Transfer Num Ops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "metric": "dfs.datanode.SendDataPacketTransferNanosNumOps",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  { "title": "Packet Round Trip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Packet Ack Round Trip Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "PacketAckRoundTripTime",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_datanode_packetackroundtriptimenanosavgtime{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Packet Round Trip Num Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "PacketAckRoundTripNumOps",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_datanode_packetackroundtriptimenanosnumops{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "diff"
    }
   ]
  },
  { "title": "Network Errors / GC Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_datanode_datanodenetworkerrors{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_datanode_gccount{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  { "title": "GC Time / GC Time ParNew", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_datanode_gctimemillis{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "GC Time mark sweep compact",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_datanode_gctimemillismarksweepcompact{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  }
 ]
}