{
 "title": "Stackstate - HDFS - Home",
 "tags": [
  "hdfs",
  "stackstate"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Files Under Construction & RPC Client Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Number of Files Under Construction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_numfilesunderconstruction{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RPC Client Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_numopenconnections{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Total File Operations & Capacity Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Total File Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_totalfileops{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_capacityusedgb{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_capacitytotalgb{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RPC Client Port Slow Calls & HDFS Total Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "RPC Client Port Slow Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_rpcslowcalls{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "HDFS Total Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_totalload{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  { "title": "Add Block Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Add Block Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_addblockavgtime{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Add Block Num Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_addblocknumops{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  }
 ]
}