{
 "title": "Stackstate - HDFS - NameNodes",
 "tags": [
  "hdfs",
  "stackstate"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "RPC Client Queue Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPC Client Port Queue Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_rpcqueuetimeavgtime{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RPC Client Port Queue Num Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_rpcqueuetimenumops{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "RPC Client Port Processing Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "RPC Client Port Processing Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_rpcprocessingtimeavgtime{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RPC Client Port Processing Num Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_rpcprocessingtimenumops{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  { "title": "GC Count & Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_gccount{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_gctimemillis{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  { "title": "GC Par New", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "GC Count Mark sweep compact",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_gccountmarksweepcompact{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "GC Time Mark sweep compact",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_gctimemillismarksweepcompact{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "GC Extra Sleep & Warning Threshold Exceeded",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "GC Extra Sleep Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_gctotalextrasleeptime{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "GC Warning Threshold Exceeded Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_gcnumwarnthresholdexceeded{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "RPC Client Port Queue & Backoff",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "RPC Client Port Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_callqueuelength{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RPC Client Port Backoff",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_rpcclientbackoff{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Transaction Since Last Edit & Checkpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }
  },
  {
   "title": "Transactions Since Last Edit Roll",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_transactionssincelastlogroll{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Transactions Since Last Checkpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_transactionssincelastcheckpoint{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Lock Queue Length & Expired Heartbeats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 }
  },
  {
   "title": "Lock Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_lockqueuelength{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Expired Heartbeats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_expiredheartbeats{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  { "title": "Threads Blocked / Waiting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Threads Blocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_threadsblocked{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Threads Waiting",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "hadoop_namenode_threadswaiting{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  }
 ]
}