global:
  receiverApiKey: "API_KEY"
image:
  registry: quay.com
  pullSecretUsername: user
  pullSecretPassword: pwd
stackstate:
  instance: "https://test.stackstate.io/"
ingress:
  enabled: true
  hosts:
    - host: myhost.com
