{{- /* Does not use common.rolebinding: Helm hook + ArgoCD annotations would conflict with common merge */ -}}
{{- if eq .Values.stackstate.components.router.mode.status "automatic" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "stackstate.router.mode.rolebinding.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: router-mode
  annotations:
    {{- if .Values.deployment.compatibleWithArgoCD }}
    argocd.argoproj.io/hook: PreSync,PostSync,PostDelete
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "-2"
    {{- else }}
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade,post-delete
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "stackstate.router.mode.serviceaccount.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "stackstate.router.mode.role.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
  {{- end }}
