{{- if include "stackstate-k8s-agent.k8sResourceCollector.enabled" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-k8s-resource-collector
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 4 }}
    app.kubernetes.io/component: k8s-resource-collector
  annotations:
{{- if .Values.k8sResourceCollector.serviceaccount.annotations }}
{{ toYaml .Values.k8sResourceCollector.serviceaccount.annotations | indent 4 }}
{{- end }}
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 4 }}
{{- end }}
