{
 "title": "StackState - HBase - Home",
 "tags": [
  "hbase",
  "stackstate"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "content": "<h4 align=\"center\">Metrics to see the overall status for the HBase cluster. Click on each row title to expand on demand to look at various metrics. </h4>\n"
  },
  { "title": "RegionServers / Regions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Num RegionServers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "max",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "sum(hbase_numregionservers{name=\"Master\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Num Dead RegionServers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "max",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "sum(hbase_numdeadregionservers{name=\"Master\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Num Regions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "sum",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "sum(hbase_regioncount{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Avg Num Regions per RegionServer",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "sum(hbase_averageload{name=\"Master\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "precision": "default"
    }
   ]
  },
  { "title": "Num Regions / Stores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Num Regions / Stores - Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "regionCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "hbase_regioncount{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    },
    {
     "aggregator": "sum",
     "alias": "storeCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "hbase_storecount{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Store File Size Change / Count - Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "storeFileSize",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_storefilesize{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Store file size - {{pod}}",
     "precision": "default"
    },
    {
     "aggregator": "sum",
     "alias": "storeFileCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "hbase_storefilecount{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Store file count - {{pod}}",
     "precision": "default"
    },
    {
     "aggregator": "sum",
     "alias": "storeFileIndexSize",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_storefileindexsize{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Store file index size - {{pod}}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "staticIndexSize",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_staticindexsize{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Static index size - {{pod}}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "staticBloomSize",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_staticbloomsize{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Static bloom size  - {{pod}}",
     "precision": "default"
    }
   ]
  },
  { "title": "Num Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Num Requests - Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "totalRequestCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_totalrequestcount{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Total request count - {{pod}}",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "readRequestCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_readrequestcount{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Read request count - {{pod}}",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "writeRequestCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_writerequestcount{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Write request count - {{pod}}",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "rpcCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_totalcalltime_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Number of operations - {{pod}}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "Num Request - Breakdown - Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "getCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_get_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "scanNextCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_scannext_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "mutateCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_mutate_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "deleteCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_delete_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "incrementCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_increment_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "appendCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_append_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "replayCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_replay_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "MemHeapMax",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "jvm_memory_bytes_max{area=\"heap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "MemHeapUsed",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "jvm_memory_bytes_used{area=\"heap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "MemHeapCommitted",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "jvm_memory_bytes_comitted{area=\"heap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "JVM Offheap Memory - Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "MemNonHeapMax",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "jvm_memory_bytes_max{area=\"nonheap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "MemNonHeapUsed",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "jvm_memory_bytes_used{area=\"nonheap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "MemNonHeapCommitted",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Memory - MemStore / BlockCache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memstore / BlockCache - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "memStoreSize",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_memstoresize{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "blockCacheSize",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_blockcachesize{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "blockCacheFreeSize",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_blockcachefreesize{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Num Blocks in BlockCache - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "blochCacheCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_blockcachecount{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      }
     ]
    }
   ]
  },
  { "title": "BlockCache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "BlockCache Hit / Miss - Rate (/minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "blockCacheHitCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_blockcachehitcount{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Block cache hit - {{pod}}",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "sum",
     "alias": "blockCacheMissCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_blockcachemisscount{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Block cache miss - {{pod}}",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "sum",
     "alias": "blockCacheEvictionCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_blockcacheevictioncount{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Block cache eviction - {{pod}}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "BlockCache Hit Percent - Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "blockCacheExpressHitPercent",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "hbase_blockcacheexpresshitpercent{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "blockCacheCountHitPercent",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "hbase_blockcachecounthitpercent{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Operation Latencies - Get / Mutate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get Latencies - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Get_mean",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_get_mean{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_median",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_get_median{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_75th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_get_75th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_95th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_get_95thpercentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_99th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_get_99th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_get_max{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_min",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_get_min{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_num_ops",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_get_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Mutate Latencies - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Mutate_mean",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_mutate_mean{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_median",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_mutate_median{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_75th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_mutate_75th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_95th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_mutate_95th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_99th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_mutate_99th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_mutate_max{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_min",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_mutate_min{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_num_ops",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_mutate_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Latencies - Delete / Increment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delete Latencies - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Delete_mean",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_delete_mean{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_median",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_delete_median{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_75th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_delete_75th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_95th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_delete_95th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_99th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_delete_99th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_delete_max{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_min",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_delete_min{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_num_ops",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_delete_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Increment Latencies - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Increment_mean",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_increment_mean{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_median",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_increment_median{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_75th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_increment_75th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_95th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_increment_95th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_99th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_increment_99th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_increment_max{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_min",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_increment_min{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_num_ops",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_increment_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Latencies - Append / Replay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Append Latencies - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Append_mean",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_append_mean{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_median",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_append_median{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_75th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_append_75th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_95th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_append_95th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_99th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_append_99th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_append_max{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_min",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_append_min{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_num_ops",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_append_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Replay Latencies - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Replay_mean",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_replay_replay_mean{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_median",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_replay_mdeian{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_75th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_replay_75th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_95th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_replay_95th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_99th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_replay_99th_percentile{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_replay_max{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_min",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_replay_min{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_num_ops",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "expr": "hbase_replay_num_ops{name=\"RegionServer\", sub=\"Server\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  { "title": "RegionServer RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "RegionServer RPC Queues - Active handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "numActiveHandler",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "hbase_numactivehandler{name=\"RegionServer\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RegionServer RPC - Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "rpcCount",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_totalcalltime_num_ops{name=\"RegionServer\",cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Number of operations - {{pod}}",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "numActiveHandler",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_numactivehandler{name=\"RegionServer\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Number of active handlers - {{pod}}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "numOpenConnections",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_numopenconnections{name=\"RegionServer\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Number of open connections - {{pod}}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "RegionServer RPC Queues - Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "numCallsInGeneralQueue",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "hbase_numcallsingeneralqueue{name=\"RegionServer\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "numCallsInPriorityQueue",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "hbase_numcallsinpriorityqueue{name=\"RegionServer\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "numCallsInReplicationQueue",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "hbase_numcallsinreplicationqueue{name=\"RegionServer\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "queueSize",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "hbase_queuesize{name=\"RegionServer\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "precision": "default"
    }
   ]
  },
  { "title": "RegionServer RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "RegionServer RPC Throughput - Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "receivedBytes",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_receivedbytes{name=\"RegionServer\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Received - {{pod}}",
     "precision": "default",
     "transform": "rate"
    },
    {
     "aggregator": "avg",
     "alias": "sentBytes",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "rate(hbase_sentbytes{name=\"RegionServer\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "Sent - {{pod}}",
     "precision": "default",
     "transform": "rate"
    }
   ]
  }
 ]
}