apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname.short" . }}
  namespace: {{.Release.Namespace}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ include "fullname.short" . }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ include "fullname.short" . }}
    spec:
      serviceAccountName: {{ include "fullname.short" . }}
    {{- if .Values.image.pullSecretName }}
      imagePullSecrets:
      - name: '{{ .Values.image.pullSecretName }}'
    {{- else if .Values.image.pullSecretUsername }}
      imagePullSecrets:
      - name: '{{ template "fullname.short" . }}-pull-secret'
    {{- end }}
      containers:
      - name: kommoner
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - start
        - -vv
        volumeMounts:
        - name: config-volume
          mountPath: /conf.d
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "fullname.short" . }}-config
