{{- if .Values.console.integrity.enabled }}

{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "hbase.console.container.main" (merge (dict "console_command" "stackgraph-console run integrity.live\\(\\).run\\(\\)") .)) -}}
{{- $stackstateHbaseConsoleContainer := (merge $overrideContainer $commonContainer) }}

{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ template "common.fullname.short" . }}-integrity
  labels:
    app.kubernetes.io/component: integrity
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.console.integrity.schedule | quote }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: integrity
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 600
      template:
        metadata:
          labels:
            app.kubernetes.io/component: integrity
        spec:
          {{- include "common.image.pullSecret.name" (dict "images" (list .Values.all.image) "context" $) | nindent 10 }}
        {{- if .Values.serviceAccount.create }}
          serviceAccountName: {{ template "common.fullname.short" . }}-console
        {{- end }}
        {{- if .Values.console.securityContext.enabled }}
          securityContext: {{- omit .Values.console.securityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
          containers:
          - {{ toYaml $stackstateHbaseConsoleContainer | nindent 12 }}
        {{- if or .Values.all.nodeSelector .Values.console.nodeSelector }}
          nodeSelector:
            {{- with .Values.all.nodeSelector }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.console.nodeSelector }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- end }}
        {{- if or .Values.all.affinity .Values.console.affinity }}
          affinity:
            {{- with .Values.all.affinity }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.console.affinity }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- end }}
        {{- if or .Values.all.tolerations .Values.console.tolerations }}
          tolerations:
            {{- with .Values.all.tolerations }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.console.tolerations }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- end }}
          restartPolicy: Never
{{- end }}
