{{- define "hbase.hbase.regionserver.container.init" -}}
name: regionserver-init
command:
- sh
- -c
- |
  /entrypoint -c {{ include "hbase.zookeeper.endpoint" . }}:2181,{{ template "common.fullname.short" . }}-hbase-master:16000 -t 300
image: "{{ include "common.image.registry" (dict "image" .Values.global.wait.image "context" .) }}/{{ .Values.global.wait.image.repository }}:{{ .Values.global.wait.image.tag }}"
imagePullPolicy: {{ .Values.global.wait.image.pullPolicy | quote }}
{{- end -}}

{{- define "hbase.hbase.regionserver.container.main" -}}
name: regionserver
image: "{{ include "common.image.registry" (dict "image" .Values.all.image "context" .) }}/{{ .Values.hbase.regionserver.image.repository }}:{{ default (printf "%s-%s" .Values.version .Values.stackgraph.version) .Values.hbase.regionserver.image.tag }}"
imagePullPolicy: {{ default .Values.stackgraph.image.pullPolicy .Values.hbase.regionserver.image.pullPolicy | quote  }}
env:
{{- include "hbase.hdfs.commonEnv" . }}
{{- include "hbase.hbase.commonEnv" . }}
{{- include "all.commonEnv" . }}
{{- include "hbase.regionserver.commonEnv" . }}
- name: POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: POD_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
- name: HBASE_CONF_hbase_regionserver_hostname
  value: $(POD_NAME).{{ template "common.fullname.short" . }}-hbase-rs.$(POD_NAMESPACE).svc.cluster.local
- name: HBASE_CONF_hbase_master_hostname
  value: "{{ template "common.fullname.short" . }}-hbase-master"
{{- $profileResources := include "common.sizing.hbase.regionserver.resources" . | trim -}}
{{- $evaluatedResources := .Values.hbase.regionserver.resources }}
{{- if $profileResources }}
{{- $profileResourcesDict := fromYaml $profileResources }}
{{- $evaluatedResources = merge $profileResourcesDict .Values.hbase.regionserver.resources }}
{{- end }}
{{- $regionserverWithResources := merge (dict "resources" $evaluatedResources) .Values.hbase.regionserver }}
{{- $serviceConfig := dict "ServiceConfig" (merge $regionserverWithResources .Values.all) }}
{{- include "hbase.service.envvars" $serviceConfig }}
ports:
- containerPort: 16020
  name: rs
- containerPort: 16030
  name: rsinfo
{{- if .Values.all.metrics.enabled }}
- containerPort: 9404
  name: metrics
{{- end }}
livenessProbe:
  exec:
    command:
      - /rs-scripts/check-status.sh
readinessProbe:
  exec:
    command:
      - /rs-scripts/check-status.sh
{{- with $evaluatedResources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
securityContext:
  runAsNonRoot: true
volumeMounts:
  - name: rs-scripts
    mountPath: /rs-scripts
{{- end -}}

{{- define "hbase.hbase.regionserver.statefulset" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "hbase.hbase.regionserver.container.main" .) -}}
{{- $stackstateHbaseRegionServerContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideContainer := fromYaml (include "hbase.hbase.regionserver.container.init" .) -}}
{{- $stackstateHbaseRegionServerInitContainer := (merge $overrideContainer $commonContainer) -}}
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: hbase-rs
{{- if .Values.global.commonLabels }}
{{- include "hbase.commonLabels" . | indent 4 }}
{{- end }}
  name: {{ template "common.fullname.short" . }}-hbase-rs
spec:
  podManagementPolicy: Parallel
  {{- $replicaCount := include "common.sizing.hbase.regionserver.effectiveReplicaCount" . }}
  replicas: {{ $replicaCount }}
  serviceName: {{ template "common.fullname.short" . }}-hbase-rs
  selector:
    matchLabels:
      app.kubernetes.io/component: hbase-rs
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/name: {{ template "common.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: hbase-rs
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/name: {{ template "common.name" . }}
{{- if .Values.global.commonLabels }}
{{- include "hbase.podLabels" . | indent 8 }}
{{- end }}
      annotations:
      {{ include "common.metrics.annotations" (dict "metrics" .Values.all.metrics "port" "9404" "container_name" "regionserver" "filter" .Values.hbase.regionserver.agentMetricsFilter) | indent 8 }}
    spec:
      {{- include "hbase.image.pullSecret.name" (dict "images" (list .Values.all.image) "context" $) | nindent 6 }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "common.fullname.short" . }}-hbase
      {{- end }}
      {{- if .Values.hbase.securityContext.enabled }}
      securityContext: {{- omit .Values.hbase.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}

      initContainers:
      - {{ toYaml $stackstateHbaseRegionServerInitContainer | nindent 8 }}
      containers:
      - {{ toYaml $stackstateHbaseRegionServerContainer | nindent 8 }}
      volumes:
        - name: rs-scripts
          configMap:
            name: {{ template "common.fullname.short" . }}-hbase-rs-scripts
            defaultMode: 0755
    {{- if or .Values.all.nodeSelector .Values.hbase.regionserver.nodeSelector }}
      nodeSelector:
      {{- with .Values.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hbase.regionserver.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- $sizingAffinity := include "common.sizing.hbase.regionserver.affinityConfig" . | fromYaml -}}
    {{- if or .Values.all.affinity .Values.hbase.regionserver.affinity $sizingAffinity }}
      affinity:
      {{- with $sizingAffinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.all.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hbase.regionserver.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.hbase.regionserver.terminationGracePeriodSeconds }}
    {{- if or .Values.all.tolerations .Values.hbase.regionserver.tolerations }}
      tolerations:
      {{- with .Values.all.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hbase.regionserver.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end -}}

{{- if eq (include "hbase.deployment.mode" .) "Distributed" -}}
apiVersion: apps/v1
kind: StatefulSet
{{ include "hbase.hbase.regionserver.statefulset" . }}
{{- end -}}
