{{- define "hbase.hdfs.secondarynamenode.container.init" -}}
name: snamenode-init
command:
- bash
- -c
- |
  /entrypoint -c {{ template "common.fullname.short" . }}-hdfs-nn-headful:9000 -t 300
  mkdir -p /hadoop-data/data
  # migrate old data directory location
  if [ -e /hadoop-data/current ]; then
    GLOBIGNORE=data:lost+found
    mv /hadoop-data/* /hadoop-data/data/
  fi
  {{- if .Values.hdfs.volumePermissions.enabled }}
  chown -R {{ .Values.hdfs.securityContext.runAsUser }}:{{ .Values.hdfs.securityContext.runAsGroup }} /hadoop-data
  {{- end }}
image: "{{ include "common.image.registry" (dict "image" .Values.wait.image "context" .) }}/{{ .Values.wait.image.repository }}:{{ .Values.wait.image.tag }}"
imagePullPolicy: {{ .Values.wait.image.pullPolicy | quote }}
{{- if .Values.hdfs.volumePermissions.securityContext.enabled }}
securityContext: {{- omit .Values.hdfs.volumePermissions.securityContext "enabled" | toYaml | nindent 2 }}
{{- end }}
volumeMounts:
- name: data
  mountPath: /hadoop-data
{{- end -}}

{{- define "hbase.hdfs.secondarynamenode.container.main" -}}
{{- $hdfsVersion := include "hdfs.version" . -}}
name: namenode
image: "{{ include "common.image.registry" (dict "image" .Values.all.image "context" .) }}/{{ .Values.hdfs.image.repository }}:{{ default (printf "%s-%s" $hdfsVersion .Values.hdfs.version) .Values.hdfs.image.tag }}"
imagePullPolicy: {{ .Values.hdfs.image.pullPolicy | quote  }}
args:
- /entrypoint.sh
- /run.sh
- secondarynamenode
env:
{{- include "hbase.hdfs.commonEnv" . }}
{{- include "all.commonEnv" . }}
{{- include "hdfs.secondarynamenode.commonEnv" . }}
{{- $profileResources := include "common.sizing.hbase.hdfs.secondarynamenode.resources" . | trim -}}
{{- $evaluatedResources := .Values.hdfs.secondarynamenode.resources }}
{{- if $profileResources }}
{{- $profileResourcesDict := fromYaml $profileResources }}
{{- $evaluatedResources = merge $profileResourcesDict .Values.hdfs.secondarynamenode.resources }}
{{- end }}
{{- $secondarynamenodeWithResources := merge (dict "resources" $evaluatedResources) .Values.hdfs.secondarynamenode }}
{{- $serviceConfig := dict "ServiceConfig" (merge $secondarynamenodeWithResources .Values.all) }}
{{- include "hbase.service.envvars" $serviceConfig }}
ports:
- containerPort: 50090
  name: snn
{{- if .Values.all.metrics.enabled }}
- containerPort: 9404
  name: metrics
{{- end }}
livenessProbe:
  tcpSocket:
    port: snn
readinessProbe:
  tcpSocket:
    port: snn
{{- with $evaluatedResources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
securityContext:
  runAsNonRoot: true
volumeMounts:
- name: data
  mountPath: /hadoop-data
{{- end -}}

{{- define "hbase.hdfs.secondarynamenode.statefulset" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "hbase.hdfs.secondarynamenode.container.main" .) -}}
{{- $stackstateHbaseHdfsSecondaryNamenodeContainer := (merge $overrideContainer $commonContainer) }}
{{- $overrideContainer := fromYaml (include "hbase.hdfs.secondarynamenode.container.init" .) -}}
{{- $stackstateHbaseHdfsSecondaryNamenodeInitContainer := (merge $overrideContainer $commonContainer) }}
metadata:
  labels:
    app.kubernetes.io/component: hdfs-snn
{{- if .Values.global.commonLabels }}
{{- include "hbase.commonLabels" . | indent 4 }}
{{- end }}
  name: {{ template "common.fullname.short" . }}-hdfs-snn
spec:
  serviceName: {{ template "common.fullname.short" . }}-hdfs-snn
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: hdfs-snn
  template:
    metadata:
      labels:
        app.kubernetes.io/component: hdfs-snn
{{- if .Values.global.commonLabels }}
{{- include "hbase.podLabels" . | indent 8 }}
{{- end }}
      annotations:
      {{ include "common.metrics.annotations" (dict "metrics" .Values.all.metrics "port" "9404" "container_name" "namenode" "filter" .Values.hdfs.secondarynamenode.agentMetricsFilter) | indent 8 }}
    spec:
      {{- include "common.image.pullSecret.name" (dict "images" (list .Values.all.image) "context" $) | nindent 6 }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "common.fullname.short" . }}-hdfs
      {{- end }}
      {{- if .Values.hdfs.securityContext.enabled }}
      securityContext: {{- omit .Values.hdfs.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - {{ toYaml $stackstateHbaseHdfsSecondaryNamenodeContainer | nindent 8 }}
      initContainers:
      - {{ toYaml $stackstateHbaseHdfsSecondaryNamenodeInitContainer | nindent 8 }}
    {{- if or .Values.all.nodeSelector .Values.hdfs.secondarynamenode.nodeSelector }}
      nodeSelector:
      {{- with .Values.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hdfs.secondarynamenode.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- $sizingAffinity := include "common.sizing.hbase.hdfs.secondarynamenode.affinityConfig" . | fromYaml -}}
    {{- if or .Values.all.affinity .Values.hdfs.secondarynamenode.affinity $sizingAffinity }}
      affinity:
      {{- with $sizingAffinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.all.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hdfs.secondarynamenode.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.all.tolerations .Values.hdfs.secondarynamenode.tolerations }}
      tolerations:
      {{- with .Values.all.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hdfs.secondarynamenode.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
      volumes:
    {{- if not .Values.hdfs.secondarynamenode.persistence.enabled }}
      - name: data
        emptyDir: {}
    {{- end }}
{{- if .Values.hdfs.secondarynamenode.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: {{ .Values.hdfs.secondarynamenode.persistence.accessModes }}
        resources:
          requests:
            storage: {{ .Values.hdfs.secondarynamenode.persistence.size }}
        {{ include "common.storage.class" ( dict "persistence" .Values.hdfs.secondarynamenode.persistence "global" .Values.global) | nindent 8 }}
{{- end }}
{{- end -}}

{{- if eq (include "hbase.deployment.mode" .) "Distributed" -}}
{{- if .Values.hdfs.secondarynamenode.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
{{ include "hbase.hdfs.secondarynamenode.statefulset" . }}
{{- end -}}
{{- end -}}
