apiVersion: v2
appVersion: 5.0.0
description: A Helm chart for Anomaly Detection
home: https://gitlab.com/stackvista/stackstate-ailab
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
keywords:
- aiops
- monitoring
- stackstate
maintainers:
- name: SUSE Observability Ops Team
  email: suse-observability-ops@suse.com
name: anomaly-detection
version: 5.2.0-snapshot.182
dependencies:
- name: common
  repository: file://../common
  version: '*'
