apiVersion: v2
appVersion: 3.0.0
version: 1.1.2
description: Helm chart for the SUSE observability Agent.
keywords:
- monitoring
- observability
- SUSE
annotations:
  catalog.cattle.io/display-name: SUSE Observability Agent
  # This fixes the release name, we fix this for ease of use of the user. Ideally we'd be able to set a default here but
  # allow the user to change this, however, ranger does not support this. If the user wants to change release name
  # that should go through helm
  catalog.cattle.io/release-name: suse-observability
  # We would like to put a default namespace here, much like the release name, but fixing both namespace and release name
  # hides does fields and allows selecting a project on rancher, which is not what we want. For now this is configurable.
  # catalog.cattle.io/namespace: suse-observability
home: https://github.com/StackVista/stackstate-agent
icon: https://raw.githubusercontent.com/StackVista/helm-charts/master/stable/suse-observability-agent/logo.svg
maintainers:
- name: SUSE
  email: ops@stackstate.com
name: suse-observability-agent
