apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stackstate-standalone.fullname" . }}-license
  labels:
{{ include "stackstate-standalone.labels" . | indent 4 }}
data:
  license.conf: |
    {
        "stackstate" : {
            "license" : {
                "key" : {{ .Values.stackstate.license.key | quote }}
            }
        }
    }
