apiVersion: v1
kind: Service
metadata:
  name: {{ include "stackstate-standalone.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "stackstate-standalone.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ui.port }}
      targetPort: ui
      protocol: TCP
      name: ui
    - port: {{ .Values.service.receiver.port }}
      targetPort: receiver
      protocol: TCP
      name: receiver
    - port: {{ .Values.service.admin.port }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app.kubernetes.io/name: {{ include "stackstate-standalone.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
