{{- define "stackstate.s3proxy.configmap" -}}
metadata:
  name: {{ include "stackstate.s3proxy.fullname" . }}-config
  labels:
    app.kubernetes.io/name: s3proxy
    app.kubernetes.io/component: s3proxy
    app.kubernetes.io/part-of: suse-observability
    {{- include "suse-observability.labels.global" . | nindent 4 }}
  {{- if include "stackstate.s3proxy.hasDeprecatedValues" . }}
  annotations:
    helm.sh/deprecation-warnings: {{ include "stackstate.s3proxy.deprecationWarnings" . | quote }}
  {{- end }}
data:
  s3proxy-settings.properties: |
    jclouds.provider=filesystem-nio2
    jclouds.filesystem.basedir=/settings-data
    s3proxy.bucket-locator.1={{ include "stackstate.s3proxy.localSettingsBucketName" . }}
  {{- if .Values.global.backup.enabled }}
  s3proxy-main.properties: |
    {{- if include "stackstate.s3proxy.mainBackendUsesPVC" . }}
    jclouds.provider=filesystem-nio2
    jclouds.filesystem.basedir=/main-data
    {{- else if include "stackstate.s3proxy.s3BackendEnabled" . }}
    jclouds.provider=aws-s3-sdk
    {{- $s3Endpoint := include "stackstate.s3proxy.s3BackendEndpoint" . }}
    {{- if ne $s3Endpoint "" }}
    jclouds.endpoint={{ $s3Endpoint }}
    {{- end }}
    aws-s3-sdk.conditional-writes=native
    {{- if not (include "stackstate.s3proxy.s3BackendAccessKey" .) }}
    jclouds.identity=
    jclouds.credential=
    {{- end }}
    {{- else if include "stackstate.s3proxy.azureBackendEnabled" . }}
    jclouds.provider=azureblob-sdk
    {{- $azureAccountName := include "stackstate.s3proxy.azureBackendAccountName" . }}
    {{- if .Values.backup.storage.backend.azure.endpoint }}
    jclouds.endpoint={{ .Values.backup.storage.backend.azure.endpoint }}
    {{- else if $azureAccountName }}
    jclouds.endpoint=https://{{ $azureAccountName }}.blob.core.windows.net
    {{- end }}
    {{- if not (include "stackstate.s3proxy.azureBackendAccountKey" .) }}
    jclouds.identity=
    jclouds.credential=
    {{- end }}
    {{- else if .Values.global.backup.enabled }}
    {{- fail "No valid backend configured for backup storage. Please enable and configure one of the supported backends (PVC, S3, Azure)." }}
    {{- end }}
    {{- $buckets := list .Values.backup.configuration.bucketName .Values.backup.stackGraph.bucketName .Values.backup.elasticsearch.bucketName .Values.clickhouse.backup.bucketName (index .Values "victoria-metrics-0" "backup" "bucketName") (index .Values "victoria-metrics-1" "backup" "bucketName") | compact | uniq }}
    {{- range $i, $bucket := $buckets }}
    s3proxy.bucket-locator.{{ add $i 1 }}={{ $bucket }}
    {{- end }}
  {{- end }}
{{- end -}}

{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $s3proxyConfigMap := fromYaml (include "stackstate.s3proxy.configmap" .) -}}
{{- toYaml (merge $s3proxyConfigMap $commonConfigMap) -}}
