{{- if not .Values.s3proxy.credentials.fromExternalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackstate.s3proxy.secretName" . }}
  labels:
    app.kubernetes.io/name: s3proxy
    app.kubernetes.io/component: s3proxy
    {{- include "suse-observability.labels.global" . | nindent 4 }}
type: Opaque
data:
  accesskey: {{ include "stackstate.s3proxy.accessKey" . | b64enc | quote }}
  secretkey: {{ include "stackstate.s3proxy.secretKey" . | b64enc | quote }}
  {{- if and .Values.global.backup.enabled (include "stackstate.s3proxy.s3BackendEnabled" .) (not .Values.backup.storage.backend.s3.fromExternalSecret) }}
  backendAccessKey: {{ include "stackstate.s3proxy.s3BackendAccessKey" . | b64enc | quote }}
  backendSecretKey: {{ include "stackstate.s3proxy.s3BackendSecretKey" . | b64enc | quote }}
  {{- end }}
  {{- if and .Values.global.backup.enabled (include "stackstate.s3proxy.azureBackendEnabled" .) (not .Values.backup.storage.backend.azure.fromExternalSecret) }}
  azureAccountName: {{ include "stackstate.s3proxy.azureBackendAccountName" . | b64enc | quote }}
  {{- if include "stackstate.s3proxy.azureBackendAccountKey" . }}
  azureAccountKey: {{ include "stackstate.s3proxy.azureBackendAccountKey" . | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
