{{- if eq (include "stackstate.s3proxy.serviceAccount.create" .) "true" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stackstate.s3proxy.serviceAccountName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: s3proxy
    app.kubernetes.io/component: s3proxy
    {{- include "suse-observability.labels.global" . | nindent 4 }}
  {{- $annotations := include "stackstate.s3proxy.serviceAccount.annotations" . -}}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
{{- end -}}
