{
 "title": "StackState Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Log Errors in StackState apps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({namespace=\"$namespace\", app=\"stackstate\"} |~ \"ERROR\" [5m])",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Log Errors in StackState dependencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({namespace=\"$namespace\", part_of=\"stackstate\"} |~ \"ERROR\" [5m])",
     "legendFormat": "Errors in StackState services"
    }
   ]
  },
  {
   "title": "Log Errors in StackState Anomaly detection",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({namespace=\"$namespace\", pod=~\".*-anomaly-detection-deployment-spotlight-.*\"} |~ \"ERROR\" [5m])",
     "legendFormat": "Errors in StackState services"
    }
   ]
  },
  {
   "title": "Api",
   "type": "logs",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", component=\"api\"}"
    }
   ]
  },
  {
   "title": "Health Sync",
   "type": "logs",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", component=\"health-sync\"}"
    }
   ]
  },
  {
   "title": "Sync",
   "type": "logs",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", component=\"sync\"}"
    }
   ]
  },
  {
   "title": "Receiver",
   "type": "logs",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", component=\"receiver\"}"
    }
   ]
  },
  {
   "title": "State",
   "type": "logs",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", component=\"state\"}"
    }
   ]
  },
  {
   "title": "view-health",
   "type": "logs",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", component=\"view-health\"}"
    }
   ]
  },
  {
   "title": "checks",
   "type": "logs",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", component=\"checks\"}"
    }
   ]
  },
  {
   "title": "Correlate",
   "type": "logs",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", component=\"correlate\"}"
    }
   ]
  },
  {
   "title": "Initializer",
   "type": "logs",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", component=\"initializer\"}"
    }
   ]
  }
 ]
}