{
 "title": "StackGraph - ReadCache and Transaction Metrics",
 "tags": [
  "stackgraph",
  "readcache",
  "transactions"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(kube_service_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "StackGraph - Retention time in minutes",
   "type": "graph",
   "description": "Numbers of seconds that last entry evicted due to size limits stay in the cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackgraph_readcache_retention_time{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"} / 60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "StackGraph - Transaction Index Lookups Seconds 98 percentile",
   "type": "graph",
   "description": "Time spent on index lookups on a transaction 98 percentile",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackgraph_index_lookup_duration_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.98\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Topology Query - Timeouts per query",
   "type": "graph",
   "description": "Execution time per query 98 percentile",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(stackstate_topology_query_timeout_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "StackGraph -  Transaction Index Lookups Seconds 95 percentile",
   "type": "graph",
   "description": "Time spent on index lookups on a transaction 95 percentile",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackgraph_index_lookup_duration_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "StackGraph - Transaction Index Lookups Seconds 75 percentile",
   "type": "graph",
   "description": "Time spent on index lookups on a transaction 75 percentile",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackgraph_index_lookup_duration_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.75\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "StackGraph - Scan Lookups Seconds 98 percentile",
   "type": "graph",
   "description": "Time spent on index lookups on a fallback from GET to SCAN 98 percentile",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackgraph_scan_index_lookup_duration_ms{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.98\"}",
     "legendFormat": "{{ rowId }}"
    }
   ]
  },
  {
   "title": "StackGraph - Scan Lookups Seconds 95 percentile",
   "type": "graph",
   "description": "Time spent on index lookups on a fallback from GET to SCAN 95 percentile",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackgraph_scan_index_lookup_duration_ms{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{ rowId }}"
    }
   ]
  },
  {
   "title": "StackGraph - Scan Lookups Seconds 75 percentile",
   "type": "graph",
   "description": "Time spent on index lookups on a fallback from GET to SCAN 75 percentile",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackgraph_scan_index_lookup_duration_ms{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.75\"}",
     "legendFormat": "{{ rowId }}"
    }
   ]
  },
  {
   "title": "Topology Query - Query Executiom time 98 percentile",
   "type": "graph",
   "description": "Execution time per query 98 percentile",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackstate_topology_query_execute_duration_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.98\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Topology Query - Query Executiom time 95 percentile",
   "type": "graph",
   "description": "Execution time per query 95 percentile",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackstate_topology_query_execute_duration_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Topology Query - Query Executiom time 75 percentile",
   "type": "graph",
   "description": "Execution time per query 75 percentile",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackstate_topology_query_execute_duration_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.75\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  }
 ]
}