{
 "title": "StackGraph - Compaction",
 "tags": [
  "stackgraph",
  "compaction",
  "slicing",
  "major compaction"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(kube_service_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "StackGraph - Slicing durations Seconds 98 percentile",
   "type": "graph",
   "description": "Time spent on slicing certain table 98 percentile",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackgraph_slicing_duration_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.98\"}",
     "legendFormat": "{{ table_type }}"
    }
   ]
  },
  {
   "title": "Sync - Sliced rows Rate",
   "type": "graph",
   "description": "Rate at which we slice rows per second of the 1 minute average",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table_type, pod)(rate(stackgraph_slicing_sliced_rows_count_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{pod}} - {{table_type}}"
    }
   ]
  },
  {
   "title": "Sync - Slicing errors Rate",
   "type": "graph",
   "description": "Rate of errors while slicing per second of the 1 minute average",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table_type, pod)(rate(stackgraph_slicing_errors_count_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{pod}} - {{table_type}}"
    }
   ]
  },
  {
   "title": "StackGraph - Slicing compaction durations Seconds 98 percentile",
   "type": "graph",
   "description": "Time spent on compaction after slicing certain table 98 percentile",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackgraph_slicing_compaction_duration_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.98\"}",
     "legendFormat": "{{ table_type }}"
    }
   ]
  },
  {
   "title": "Sync - Compaction errors Rate",
   "type": "graph",
   "description": "Rate of errors while compaction per second of the 1 minute average",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table_type, pod)(rate(stackgraph_slicing_compaction_errors_count_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{pod}} - {{table_type}}"
    }
   ]
  },
  {
   "title": "Sync - Compaction completed Rate",
   "type": "graph",
   "description": "Rate of errors while compaction per second of the 1 minute average",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table, pod)(rate(hbase_compactionscompletedcount{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", name=\"RegionServer\", sub=\"Regions\"}[1m]))",
     "legendFormat": "{{pod}} - {{table}}"
    }
   ]
  },
  {
   "title": "Sync - Major compacted cells Rate",
   "type": "graph",
   "description": "Rate of cells compacted by major compaction per second of the 1 minute average",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table, pod)(rate(hbase_majorcompactedcellscount{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", name=\"RegionServer\", sub=\"Server\",}[1m]))",
     "legendFormat": "{{pod}} - {{table}}"
    }
   ]
  },
  {
   "title": "Sync - Major compacted cells Rate",
   "type": "graph",
   "description": "Rate of cells compacted by minor compaction per second of the 1 minute average",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table, pod)(rate(hbase_compactedcellscount{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", name=\"RegionServer\", sub=\"Server\",}[1m]))",
     "legendFormat": "{{pod}} - {{table}}"
    }
   ]
  },
  {
   "title": "Sync - Compaction queue length",
   "type": "graph",
   "description": "Compaction queue length",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hbase_compactionqueuelength{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", name=\"RegionServer\", sub=\"Server\",}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Sync - Num files compacted Rate",
   "type": "graph",
   "description": "Rate of num files compacted per second of the 1 minute average",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table, pod)(rate(hbase_numfilescompactedcount{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", name=\"RegionServer\", sub=\"Regions\",}[1m]))",
     "legendFormat": "{{pod}} - {{table}}"
    }
   ]
  }
 ]
}