apiVersion: v2
appVersion: "7.0.0-snapshot.20250728115032-master-8db9233"
version: 2.3.7-pre.17
description: Helm chart for SUSE Observability
keywords:
  - kubernetes
  - observability
  - suse
home: https://gitlab.com/stackvista/stackstate.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: SUSE
    email: ops@stackstate.com
name: suse-observability
dependencies:
  - name: anomaly-detection
    # chart source: https://gitlab.com/stackvista/stackstate-ailab/-/tree/master/.helm/stable/anomaly-detection

    # For local debugging
    # repository: file:///home/bram/stackvista/stackstate-ailab/.helm/stable/anomaly-detection/
    # version: "*"
    version: 5.2.0-snapshot.164
    repository: https://helm.stackstate.io
    condition: anomaly-detection.enabled
  - name: common
    repository: file://../common/
    version: "*"
  - name: elasticsearch
    condition: elasticsearch.enabled
    repository: file://../elasticsearch/
    # For some reason * does not work
    version: "8.11.4-stackstate.5"
  - name: hbase
    condition: hbase.enabled
    repository: file://../hbase/
    version: "0.2.64"
  - name: kafka
    condition: kafka.enabled
    # Bitnami official Helm repository stopped serving the old versions of the charts. This is the workaround https://github.com/bitnami/charts/issues/10539
    # repository: https://charts.bitnami.com/bitnami
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    version: 19.1.3
  - name: kafkaup-operator
    condition: kafkaup-operator.enabled
    repository: file://../kafkaup-operator/
    version: "*"
  - name: minio
    repository: file://../minio/
    # For some reason * does not work
    version: "8.0.10-stackstate.11"
    condition: backup.enabled
  - name: pull-secret
    version: "*"
    repository: file://../pull-secret/
    condition: pull-secret.enabled
  - name: zookeeper
    version: 8.1.2
    # Bitnami official Helm repository stopped serving the old versions of the charts. This is the workaround https://github.com/bitnami/charts/issues/10539
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: zookeeper.enabled
  - name: victoria-metrics-single
    alias: victoria-metrics-0
    version: "0.8.53-stackstate.21"
    repository: file://../victoria-metrics-single/
    condition: victoria-metrics-0.enabled
  - name: victoria-metrics-single
    alias: victoria-metrics-1
    version: "0.8.53-stackstate.21"
    repository: file://../victoria-metrics-single/
    condition: victoria-metrics-1.enabled
  - name: victoria-metrics-cluster
    alias: victoriametrics-cluster
    repository: file://../victoria-metrics-cluster
    version: 0.14.6-stackstate.1
    condition: victoriametrics-cluster.enabled
  - name: clickhouse
    version: 3.6.9
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: clickhouse.enabled
  - name: opentelemetry-collector
    version: 0.108.0-stackstate.0
    repository: file://../opentelemetry-collector
    condition: opentelemetry.enabled
  - name: kubernetes-rbac-agent
    # chart source: https://gitlab.com/stackvista/agent/kubernetes-rbac-agent/-/tree/main/charts/kubernetes-rbac-agent

    # Local debugging: left here for future reference
    # repository: file:///home/bram/stackvista/agent/kubernetes-rbac-agent/charts/kubernetes-rbac-agent
    # version: "*"
    repository: https://helm.stackstate.io
    version: 0.0.14
    condition: stackstate.k8sAuthorization.enabled
