apiVersion: v2
appVersion: "7.0.0-snapshot.20260226153654-master-c1dce84"
version: 2.7.1-pre.102
description: Helm chart for SUSE Observability
keywords:
  - kubernetes
  - observability
  - suse
home: https://gitlab.com/stackvista/stackstate.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: SUSE
    email: suse-observability-ops@suse.com
name: suse-observability
dependencies:
  - name: anomaly-detection
    # chart source: https://gitlab.com/stackvista/stackstate-ailab/-/tree/master/.helm/stable/anomaly-detection

    # For local debugging
    # repository: file:///home/bram/stackvista/stackstate-ailab/.helm/stable/anomaly-detection/
    # version: "*"
    version: 5.2.0-snapshot.179
    repository: https://helm.stackstate.io
    condition: anomaly-detection.enabled
  - name: common
    repository: file://../common/
    version: "*"
  - name: suse-observability-sizing
    repository: file://../suse-observability-sizing/
    version: 0.1.6
  - name: elasticsearch
    condition: elasticsearch.enabled
    repository: file://../elasticsearch/
    # For some reason * does not work
    version: "8.19.4-stackstate.10"
  - name: hbase
    condition: hbase.enabled
    repository: file://../hbase/
    version: "0.2.120"
  - name: kafka
    condition: kafka.enabled
    repository: file://../kafka/
    version: 19.1.3-suse-observability.12
  - name: kafkaup-operator
    condition: kafkaup-operator.enabled
    repository: file://../kafkaup-operator/
    version: "0.1.18"
  - name: minio
    repository: file://../minio/
    # For some reason * does not work
    version: "8.0.10-stackstate.19"
    condition: global.backup.enabled
  - name: pull-secret
    version: "*"
    repository: file://../pull-secret/
    condition: pull-secret.enabled
  - name: zookeeper
    version: 8.1.2-suse-observability.10
    repository: file://../zookeeper/
    condition: zookeeper.enabled
  - name: victoria-metrics-single
    alias: victoria-metrics-0
    version: "0.8.53-stackstate.38"
    repository: file://../victoria-metrics-single/
    condition: victoria-metrics-0.enabled
  - name: victoria-metrics-single
    alias: victoria-metrics-1
    version: "0.8.53-stackstate.38"
    repository: file://../victoria-metrics-single/
    condition: victoria-metrics-1.enabled
  - name: clickhouse
    version: 3.6.9-suse-observability.13
    repository: file://../clickhouse/
    condition: clickhouse.enabled
  - name: opentelemetry-collector
    version: 0.108.0-stackstate.20
    repository: file://../opentelemetry-collector
    condition: opentelemetry.enabled
  - name: kubernetes-rbac-agent
    # chart source: https://gitlab.com/stackvista/agent/kubernetes-rbac-agent/-/tree/main/charts/kubernetes-rbac-agent

    # Local debugging: left here for future reference
    # repository: file:///home/bram/stackvista/agent/kubernetes-rbac-agent/charts/kubernetes-rbac-agent
    # version: "*"
    # Docker image tag now being overridden in the values file to make automated security updates possible.
    repository: https://helm.stackstate.io
    version: 0.0.25
    condition: stackstate.k8sAuthorization.enabled
