{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "elasticsearch.role.fullname" . | quote }}
  labels:
    {{- include "elasticsearch.labels.recommended" . | nindent 4 }}
    {{- include "elasticsearch.labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "elasticsearch.podsecuritypolicy.fullname" . | quote }}
    verbs:
      - use
{{- end -}}
