{{- if .Values.carts.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-db
  labels:
    {{- include "component.common.labels" ("carts-db") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "component.common.labels" ("carts-db") | nindent 6 }}
  template:
    metadata:
      {{- include "component.custom.annotations" .Values.cartsDB | nindent 6 }}
      labels:
        {{- include "component.common.labels" ("carts-db") | nindent 8 }}
        domain: business
        job: carts
        mongodb: "true"
    spec:
      serviceAccountName: sock-shop
      containers:
      - name: carts-db
        image: mongo:4.4.16
        resources:
        {{- toYaml .Values.cartsDB.resources | nindent 10 }}
        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          readOnlyRootFilesystem: false
          {{- if not .Values.all.securityCapabilitiesDisabled }}
          capabilities:
            drop:
            - all
            add:
            - CHOWN
            - SETGID
            - SETUID
          {{- end }}
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
      - name: tmp-volume
        emptyDir:
          medium: Memory
      {{- if .Values.cartsDB.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.cartsDB.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.cartsDB.tolerations }}
      tolerations:
{{ toYaml .Values.cartsDB.tolerations | indent 6 }}
      {{- end }}
{{- end }}
