{{- if .Values.locust.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: loadtest-locustfile
data:
  main.py: |+
    # -*- coding: utf-8 -*-

    from locust import HttpUser, task, between

    default_headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36', 'Connection':'close'}


    class WebsiteUser(HttpUser):
        wait_time = between(1, 5)

        @task(10)
        def get_catalogue(self):
            self.client.get("/catalogue", headers=default_headers)

        @task(2)
        def get_catalogue_slow(self):
            self.client.get("/catalogue?fetchSockMeta=true", headers=default_headers)
{{- end }}
