{{- if .Values.orders.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  labels:
    {{- include "component.common.labels" ("orders-db") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "component.common.labels" ("orders-db") | nindent 6 }}
  template:
    metadata:
      {{- include "component.custom.annotations" .Values.ordersDB | nindent 6 }}
      labels:
        {{- include "component.common.labels" ("orders-db") | nindent 8 }}
        domain: business
        job: orders-db
        mongodb: "true"
    spec:
      serviceAccountName: sock-shop
      containers:
      - name: orders-db
        image: mongo:4.4.16
        resources:
        {{- toYaml .Values.ordersDB.resources | nindent 10 }}
        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          readOnlyRootFilesystem: false
          {{- if not .Values.all.securityCapabilitiesDisabled }}
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          {{- end }}
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      {{- if .Values.ordersDB.tolerations }}
      tolerations:
{{ toYaml .Values.ordersDB.tolerations | indent 6 }}
      {{- end }}
{{- end }}
