{{- if .Values.payment.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    {{- include "component.common.labels" ("payment") | nindent 4 }}
    {{- include "sock-shop.common.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "component.common.labels" ("payment") | nindent 6 }}
  template:
    metadata:
      {{- include "component.custom.annotations" .Values.payment | nindent 6 }}

      labels:
        {{- include "component.common.labels" ("payment") | nindent 8 }}
        api_service: "true"
        domain: business
        go: "true"
        job: payment
        payment: "true"
    spec:
      serviceAccountName: sock-shop
      containers:
      - name: payment
        image: "{{ .Values.payment.image.repository }}:{{ .Values.payment.image.tag }}"
        resources:
        {{- toYaml .Values.payment.resources | nindent 10 }}
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          readOnlyRootFilesystem: true
          {{- if not .Values.all.securityCapabilitiesDisabled }}
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 3
      priorityClassName: {{ template "priority-class-name" . }}
      {{- if .Values.payment.tolerations }}
      tolerations:
{{ toYaml .Values.payment.tolerations | indent 6 }}
      {{- end }}
{{- end }}
