{
 "title": "StackState - Checks",
 "tags": [
  "stackstate",
  "checks"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(kube_service_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Check - Changes Rate",
   "type": "graph",
   "description": "Rate per second of the 1 minute average",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (check_name, pod)(rate(stackstate_check_change_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{pod}} - {{check_name}}"
    }
   ]
  },
  {
   "title": "Check - Error Rate",
   "type": "graph",
   "description": "Rate per second of the 1 minute average",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (check_name, pod)(rate(stackstate_check_error_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{pod}} - {{check_name}}"
    }
   ]
  },
  {
   "title": "Check - Run Rate",
   "type": "graph",
   "description": "Rate per second of the 1 minute average",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (check_name, pod)(rate(stackstate_check_run_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{pod}} - {{check_name}}"
    }
   ]
  }
 ]
}