all:
  metrics:
    enabled: true
  servicemonitor:
    enabled: true
hbase:
  master:
    metrics:
      servicemonitor:
        enabled: true
  regionserver:
    metrics:
      servicemonitor:
        enabled: true
hdfs:
  namenode:
    highAvailability:
      enabled: true
tephra:
  metrics:
    servicemonitor:
      enabled: true
zookeeper:
  enabled: true
