{{- if include "stackstate-k8s-agent.k8sResourceCollector.enabled" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-k8s-resource-collector
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 4 }}
    app.kubernetes.io/component: k8s-resource-collector
  annotations:
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 13133
      targetPort: 13133
      protocol: TCP
      name: health
  selector:
    app.kubernetes.io/component: k8s-resource-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "stackstate-k8s-agent.name" . }}
{{- end }}
