apiVersion: v1
kind: ConfigMap
metadata:
  name: suse-observability-clickhouse-backup-scripts
data:
  full-backup.sh: |
    {{- .Files.Get "scripts/backup-clickhouse-full-backup.sh" | nindent 4 }}
  incremental-backup.sh: |
    {{- .Files.Get "scripts/backup-clickhouse-incremental-backup.sh" | nindent 4 }}
