{
 "title": "StackState - Kafka",
 "tags": [
  "kafka",
  "stackstate"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values({namespace=\"$namespace\"}, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Broker total bytes sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_bytesoutpersec_oneminuterate",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Broker count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 1, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "kafka_brokers" }
   ]
  },
  {
   "title": "Broker total bytes received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_bytesinpersec_oneminuterate",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Consumer lag max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{namespace=\"$namespace\", topic=~\"$topic\"}",
     "legendFormat": "{{pod}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Records consumed rate (count/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{namespace=\"$namespace\", topic=~\"$topic\"}",
     "legendFormat": "{{pod}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Records Consumed rate (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{namespace=\"$namespace\", topic=~\"$topic\"}",
     "legendFormat": "{{pod}} - {{topic}}"
    }
   ]
  },
  { "title": "Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Producer rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_send_rate{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}} - {{consumer}}"
    }
   ]
  }
 ]
}