{
 "title": "StackState - Websockets",
 "tags": [
  "stackstate",
  "websockets"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(kube_service_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Streams - Errors Total",
   "type": "graph",
   "description": "Errors are reported over a still active stream to the client, while the stream remains active",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service, stream_type)(stackstate_websockets_stream_errors_totals{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "{{service}} - {{stream_type}}"
    }
   ]
  },
  {
   "title": "Streams - Errors Total Rate",
   "type": "graph",
   "description": "Errors are reported over a still active stream to the client, while the stream remains active",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service, stream_type)(rate(stackstate_websockets_stream_errors_totals{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{service}} - {{stream_type}}"
    }
   ]
  },
  {
   "title": "Telemetry - Errors Total - 1m Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service, datasource)(rate(stackstate_telemetry_stream_errors_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{service}} - {{datasource}}"
    }
   ]
  },
  {
   "title": "Streams - Failures Total",
   "type": "graph",
   "description": "Failures stop a stream completely, the client will need to restart the stream",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service, stream_type)(stackstate_websockets_stream_failures_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "{{service}} - {{stream_type}}"
    }
   ]
  },
  {
   "title": "Streams - Failures Total Rate",
   "type": "graph",
   "description": "Failures stop a stream completely, the client will need to restart the stream",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service, stream_type)(rate(stackstate_websockets_stream_failures_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{service}} - {{stream_type}}"
    }
   ]
  },
  {
   "title": "Streams - Time to first message Duration Seconds (98th percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackstate_websockets_stream_time_to_first_message_duration_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\",quantile=~\"0.98\"}",
     "legendFormat": "{{service}} - {{stream_type}}"
    }
   ]
  },
  {
   "title": "Streams - Rate of stream starts per 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service, stream_type)(rate(stackstate_websockets_stream_time_to_first_message_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{service}} - {{stream_type}}"
    }
   ]
  },
  {
   "title": "Streams - View Stream Start Duration Seconds (98th percentile)",
   "type": "graph",
   "description": "The view stream sends 2 initial messages, this shows the timing for both message separately",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackstate_websockets_view_stream_start_duration_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=~\"0.98\"}",
     "legendFormat": "{{service}} - {{stream_type}}"
    }
   ]
  },
  {
   "title": "Telemetry - Time to first data Duration Seconds (98th percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackstate_telemetry_stream_time_to_first_data_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\",quantile=~\"0.98\"}",
     "legendFormat": "{{service}} - {{datasource}}"
    }
   ]
  },
  {
   "title": "Telemetry - Rate of telemetry stream starts per 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service, datasource)(rate(stackstate_telemetry_stream_time_to_first_data_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{service}} - {{datasource}}"
    }
   ]
  },
  {
   "title": "Telemetry - Errors Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service, datasource)(stackstate_telemetry_stream_errors_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "{{service}} - {{datasource}}"
    }
   ]
  }
 ]
}