apiVersion: v2
appVersion: 1.2.12
version: 0.1.123
description: Helm chart for StackState HBase -- includes Zookeeper, and Hadoop for persistent storage.
keywords:
- aiops
- monitoring
- stackstate
- hbase
- hadoop
home: https://gitlab.com/stackvista/devops/helm-charts.git
sources:
- https://github.com/apache/hadoop
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
- name: Jeroen van Erp
  email: jvanerp@stackstate.com
- name: Remco Beckers
  email: rbeckers@stackstate.com
- name: Vincent Partington
  email: vpartington@stackstate.com
name: hbase
dependencies:
- name: common
  version: 0.4.19
  repository: https://helm.stackstate.io/
- name: zookeeper
  version: 5.3.4
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.enabled
