apiVersion: v1
appVersion: 2.7.3
version: 0.1.0
description: HBase Helm to deploy the distributed versions of warp10
keywords:
  - aiops
  - monitoring
  - stackstate
  - hbase
  - hadoop
home: https://gitlab.com/stackvista/devops/helm-charts.git
sources:
- https://github.com/apache/hadoop
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: sc250024
    email: scrooks@stackstate.com
name: hbase
