apiVersion: v2
appVersion: 1.2.12
version: 0.1.155+sts.5.1.x.002
description: Helm chart for StackState HBase -- includes Zookeeper, and Hadoop for persistent storage.
keywords:
- aiops
- monitoring
- stackstate
- hbase
- hadoop
home: https://gitlab.com/stackvista/devops/helm-charts.git
sources:
- https://github.com/apache/hadoop
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
- name: Stackstate Ops Team
  email: ops@stackstate.com
name: hbase
dependencies:
- name: common
  version: "*"
  repository: file://../common/
- name: zookeeper
  version: 8.1.2
  # Bitnami official Helm repository stopped serving the old versions of the charts. This is the workaround https://github.com/bitnami/charts/issues/10539
  # repository: https://charts.bitnami.com/bitnami
  repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
  condition: zookeeper.enabled
