apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cluster-agent.labels" . | indent 4 }}
type: Opaque
data:
  sts-api-key: {{ .Values.stackstate.apiKey | b64enc | quote }}
{{- if .Values.stackstate.cluster.authToken }}
  sts-cluster-auth-token: {{ .Values.stackstate.cluster.authToken | b64enc | quote }}
{{- else }}
  sts-cluster-auth-token: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
{{- range $key, $value := .Values.global.extraEnv.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
