apiVersion: v2
name: suse-observability-sizing
version: 0.1.6
description: SUSE Observability sizing profile templates library
keywords:
  - suse-observability
  - sizing
  - profiles
  - affinity
maintainers:
  - name: Stackstate Ops Team
    email: ops@stackstate.com
