{
 "title": "StackState - Amplifier Performance",
 "tags": [
  "stackstate",
  "performance-champagne"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(kube_service_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Receiver - Connected agent count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "expr": "stackstate_receiver_unique_element_passed_count{cluster=\"$cluster\", namespace=\"$namespace\", element_type=\"agent\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Receiver - Element budget saturation",
   "type": "graph",
   "description": "Percentage of agent element processing budget filled up",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_unique_element_passed_count{cluster=\"$cluster\", namespace=\"$namespace\"} / stackstate_receiver_unique_element_passed_max{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Ignored Changes Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (integration_type, pod)(rate(stackstate_sync_ignored_changes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{pod}} - {{integration_type}}"
    }
   ]
  },
  {
   "title": "Sync - Latency Seconds",
   "type": "graph",
   "description": "Time taken from collecting the data (in agent for example) until persisting in topology",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackstate_sync_latency_seconds{cluster=\"$cluster\", namespace=\"$namespace\", quantile=\"0.98\"}",
     "legendFormat": "{{pod}} - {{integration_type}}"
    }
   ]
  },
  {
   "title": "Receiver - Current incoming element (approximate) count",
   "type": "graph",
   "description": "Amount of data being offered to the receiver at this moment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_unique_element_request_approx_count{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Receiver - Incoming created elements in the last hour (approximate) count",
   "type": "graph",
   "description": "Amount of created in the past hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_element_create_request_approx_count{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{element_type}}"
    },
    {
     "expr": "stackstate_receiver_element_create_passed_max{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{element_type}} budget"
    }
   ]
  },
  {
   "title": "Receiver - Created elements hourly budget saturation",
   "type": "graph",
   "description": "Percentage of newly created elements budget filled up",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_element_create_passed_count{cluster=\"$cluster\", namespace=\"$namespace\"} / stackstate_receiver_element_create_passed_max{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Receiver - Created elements hourly total",
   "type": "graph",
   "description": "Total elements created",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_element_create_passed_count{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "ES - Used disk space",
   "type": "graph",
   "description": "ES Used disk space",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=\"data-stackstate-performance-elasticsearch-master-0\"})",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Datanode - Used disk space",
   "type": "graph",
   "description": "Datanode Used disk space",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_available_bytes{cluster=\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=\"data-stackstate-performance-hbase-hdfs-dn-0\"})",
     "legendFormat": "{{element_type}}"
    }
   ]
  }
 ]
}