{
 "title": "StackState - Receiver",
 "tags": [
  "stackstate",
  "receiver"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(kube_service_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Receiver - Current incoming element (approximate) count",
   "type": "graph",
   "description": "Amount of data being offered to the receiver at this moment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_unique_element_request_approx_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Receiver - Incoming created elements in the last hour (approximate) count",
   "type": "graph",
   "description": "Amount of created in the past hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_element_create_request_approx_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{element_type}}"
    },
    {
     "expr": "stackstate_receiver_element_create_passed_max{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{element_type}} budget"
    }
   ]
  },
  {
   "title": "Receiver - Element budget saturation",
   "type": "graph",
   "description": "Percentage of agent element processing budget filled up",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_unique_element_passed_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"} / stackstate_receiver_unique_element_passed_max{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Receiver - Created elements hourly budget saturation",
   "type": "graph",
   "description": "Percentage of newly created elements budget filled up",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_element_create_passed_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"} / stackstate_receiver_element_create_passed_max{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Receiver - Connected agent count",
   "type": "graph",
   "description": "Number of currently connected agents",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_unique_element_passed_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", element_type=\"agent\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Receiver - Created elements hourly total",
   "type": "graph",
   "description": "Total elements created",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_element_create_passed_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  }
 ]
}