{{- if and (include "stackstate-k8s-agent.otelTelemetryGateway.enabled" .) (gt (.Values.otel.telemetryGateway.replicaCount | int) 1) }}
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "stackstate-k8s-agent.otelTelemetryGateway.name" . }}
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 4 }}
    app.kubernetes.io/component: otel-telemetry-gateway
  annotations:
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
{{ include "stackstate-k8s-agent.otelTelemetryGateway.selectorLabels" . | indent 6 }}
{{- end }}
