apiVersion: v2
appVersion: 5.0.0-snapshot.0
version: 5.0.0-snapshot.1
description: Helm chart for StackState
keywords:
  - aiops
  - monitoring
  - stackstate
home: https://gitlab.com/stackvista/stackstate.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: Jeroen van Erp
    email: jvanerp@stackstate.com
  - name: Remco Beckers
    email: rbeckers@stackstate.com
  - name: Vincent Partington
    email: vpartington@stackstate.com
name: stackstate
dependencies:
  - name: anomaly-detection
    version: 5.0.0-pre.4
    repository: https://helm.stackstate.io
    condition: anomaly-detection.enabled
  - name: cluster-agent
    repository: https://helm.stackstate.io
    version: 1.0.5
    condition: cluster-agent.enabled
  - name: common
    repository: file://../common/
    version: "*"
  - name: elasticsearch
    condition: elasticsearch.enabled
    repository: https://helm.stackstate.io
    version: 7.17.2-stackstate.0
  - name: hbase
    condition: hbase.enabled
    repository: file://../hbase/
    version: "*"
  - name: kafka
    condition: kafka.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 14.8.1
  - name: kafkaup-operator
    condition: kafkaup-operator.enabled
    repository: https://helm.stackstate.io
    version: 0.1.2
  - name: minio
    repository: https://helm.stackstate.io
    version: 8.0.10-stackstate.3
    condition: backup.enabled
  - name: pull-secret
    version: 1.0.0
    repository: https://helm.stackstate.io
    condition: pull-secret.enabled
  - name: zookeeper
    version: 5.16.0
    repository: https://charts.bitnami.com/bitnami
    condition: zookeeper.enabled
