apiVersion: v2
appVersion: 5.1.13-rc.2
version: 5.1.13-rc.2
description: Helm chart for StackState
keywords:
  - aiops
  - monitoring
  - stackstate
home: https://gitlab.com/stackvista/stackstate.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: Stackstate Ops Team
    email: ops@stackstate.com
name: stackstate
dependencies:
  - name: anomaly-detection
    version: 5.1.13-rc.2
    repository: https://helm.stackstate.io
    condition: anomaly-detection.enabled
  - name: stackstate-agent
    repository: file://../stackstate-agent/
    version: "*"
    condition: stackstate-agent.enabled
  - name: common
    repository: file://../common/
    version: "*"
  - name: elasticsearch
    condition: elasticsearch.enabled
    repository: https://helm.stackstate.io
    version: 8.5.1-stackstate.2
  - name: hbase
    condition: hbase.enabled
    repository: file://../hbase/
    version: "0.1.155+sts.5.1.x.002"
  - name: kafka
    condition: kafka.enabled
    # Bitnami official Helm repository stopped serving the old versions of the charts. This is the workaround https://github.com/bitnami/charts/issues/10539
    # repository: https://charts.bitnami.com/bitnami
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    version: 15.5.1
  - name: kafkaup-operator
    condition: kafkaup-operator.enabled
    repository: file://../kafkaup-operator/
    version: "*"
  - name: minio
    repository: https://helm.stackstate.io
    version: "8.0.10-stackstate.8"
    condition: backup.enabled
  - name: pull-secret
    version: "*"
    repository: file://../pull-secret/
    condition: pull-secret.enabled
  - name: zookeeper
    version: 8.1.2
    # Bitnami official Helm repository stopped serving the old versions of the charts. This is the workaround https://github.com/bitnami/charts/issues/10539
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: zookeeper.enabled
