apiVersion: v2
appVersion: 4.6.2-rc.1
version: 4.6.2-rc.1
description: Helm chart for StackState
keywords:
  - aiops
  - monitoring
  - stackstate
home: https://gitlab.com/stackvista/stackstate.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: Jeroen van Erp
    email: jvanerp@stackstate.com
  - name: Remco Beckers
    email: rbeckers@stackstate.com
  - name: Vincent Partington
    email: vpartington@stackstate.com
name: stackstate
dependencies:
  - name: anomaly-detection
    version: 4.6.2-rc.1
    repository: https://helm.stackstate.io
    condition: anomaly-detection.enabled
  - name: cluster-agent
    repository: https://helm.stackstate.io
    version: 0.5.3
    condition: cluster-agent.enabled
  - name: common
    repository: https://helm.stackstate.io
    version: 0.4.17
  - name: elasticsearch
    condition: elasticsearch.enabled
    repository: https://helm.stackstate.io
    version: 7.16.2-stackstate.2
  - name: hbase
    condition: hbase.enabled
    repository: https://helm.stackstate.io
    version: 0.1.121
  - name: kafka
    condition: kafka.enabled
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    version: 14.8.1
  - name: kafkaup-operator
    condition: kafkaup-operator.enabled
    repository: https://helm.stackstate.io
    version: 0.1.2
  - name: minio
    repository: https://helm.stackstate.io
    version: 8.0.10-stackstate.2
    condition: backup.enabled
  - name: pull-secret
    version: 1.0.0
    repository: https://helm.stackstate.io
    condition: pull-secret.enabled
  - name: zookeeper
    version: 5.16.0
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: zookeeper.enabled
