apiVersion: v1
version: 0.1.0
appVersion: 2.4.0
name: stackstate-kafka
description: StackState Kafka Helm chart that can pre-create topics as well
maintainers:
  - name: rbeckers
    email: rbeckers@stackstate.com
home: https://gitlab.com/stackvista/stackstate.git
icon: https://bitnami.com/assets/stacks/kafka/img/kafka-stack-110x117.png
