{{- if and .Values.server.enabled .Values.server.statefulSet.enabled (eq (include "victoria-metrics.isEnabled" .) "true") -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
{{- if .Values.server.annotations }}
  annotations:
{{ toYaml .Values.server.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "victoria-metrics.server.labels" . | nindent 4 }}
    {{- include "victoria-metrics.server.statefulsetLabels" . | nindent 4 }}
    {{- include "victoria-metrics.server.scaleDownRestoreLabels" . | nindent 4 }}
  name: {{ template "victoria-metrics.server.fullname" . }}
spec:
  serviceName: {{ template "victoria-metrics.server.fullname" . }}
  selector:
    matchLabels:
      {{- include "victoria-metrics.server.matchLabels" . | nindent 6 }}
  replicas: 1
  podManagementPolicy: {{ .Values.server.podManagementPolicy }}
  template:
    metadata:
    {{- if .Values.server.podAnnotations }}
      annotations:
{{ toYaml .Values.server.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        {{- include "victoria-metrics.server.labels" . | nindent 8 }}
        {{- include "victoria-metrics.server.podLabels" . | nindent 8 }}
    spec:
{{- if .Values.server.priorityClassName }}
      priorityClassName: "{{ .Values.server.priorityClassName }}"
{{- end }}
{{- if .Values.server.schedulerName }}
      schedulerName: "{{ .Values.server.schedulerName }}"
{{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
      initContainers:
        {{- if .Values.global.backup.enabled }}
        - name: create-crontab
          image: {{ include "victoria-metrics.image.registry" (dict "image" .Values.backup.setupCron.image "context" $) }}/{{ .Values.backup.setupCron.image.repository }}:{{ .Values.backup.setupCron.image.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
          args:
            - -c
            - 'echo "$INCREMENTAL_PATTERN BUCKET_NAME=$BUCKET_NAME S3_PREFIX=$S3_PREFIX S3_ENDPOINT=$S3_ENDPOINT /app/crontab/scripts/run-victoria-metrics-backup.sh" > /app/crontab/vmbackup'
          resources:
{{ toYaml .Values.backup.setupCron.resources | indent 12 }}
          env:
            - name: INCREMENTAL_PATTERN
              value: "{{ tpl .Values.backup.scheduled.schedule . }}"
            - name: BUCKET_NAME
              value: "{{ tpl .Values.backup.bucketName . }}"
            - name: S3_ENDPOINT
              value: "{{ tpl .Values.backup.overrideS3Endpoint . }}"
            - name: S3_PREFIX
              value: {{ tpl .Values.backup.s3Prefix . | quote }}
          securityContext:
            {{- $commonContainer.securityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: crontab
              mountPath: /app/crontab
        {{- end }}
        {{- if eq (include "victoria-metrics.hasInitContainer" . ) "true" }}
        {{- include "victoria-metrics.initContiners" . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ template "victoria-metrics.name" . }}-{{ .Values.server.name }}
          {{- with  .Values.server.podSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "victoria-metrics.image.registry" (dict "image" .Values.server.image "context" $) }}/{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}
          imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
          {{- if .Values.server.containerWorkingDir }}
          workingDir: {{ .Values.server.containerWorkingDir }}
          {{- end }}
          args:
            {{- $retention := include "common.sizing.victoria-metrics.retention" . | trim -}}
            {{- if $retention }}
            - {{ printf "%s=%s" "--retentionPeriod" $retention | quote}}
            {{- else }}
            - {{ printf "%s=%s" "--retentionPeriod" (toString .Values.server.retentionPeriod) | quote}}
            {{- end }}
            - {{ printf "%s=%s" "--storageDataPath" .Values.server.persistentVolume.mountPath | quote}}
          {{- if .Values.server.scrape.enabled }}
            - -promscrape.config=/scrapeconfig/scrape.yml
          {{- end }}
          {{- range $key, $value := .Values.server.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          {{- with .Values.server.env }}
          env: {{ toYaml . | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8428
          {{- if .Values.server.extraArgs.graphiteListenAddr }}
            - name: graphite-tcp
              protocol: TCP
              containerPort: {{ include "split-host-port" .Values.server.extraArgs.graphiteListenAddr }}
          {{- end }}
          {{- if .Values.server.extraArgs.graphiteListenAddr }}
            - name: graphite-udp
              protocol: UDP
              containerPort: {{ include "split-host-port" .Values.server.extraArgs.graphiteListenAddr }}
          {{- end }}
          {{- if .Values.server.extraArgs.influxListenAddr }}
            - name: influx-tcp
              protocol: TCP
              containerPort: {{ include "split-host-port" .Values.server.extraArgs.influxListenAddr }}
          {{- end }}
          {{- if .Values.server.extraArgs.influxListenAddr }}
            - name: influx-udp
              protocol: UDP
              containerPort: {{ include "split-host-port" .Values.server.extraArgs.influxListenAddr }}
          {{- end }}
          {{- if .Values.server.extraArgs.opentsdbHTTPListenAddr }}
            - name: opentsdbhttp
              protocol: TCP
              containerPort: {{ include "split-host-port" .Values.server.extraArgs.opentsdbHTTPListenAddr }}
          {{- end }}
          {{- if .Values.server.extraArgs.opentsdbListenAddr }}
            - name: opentsdb-tcp
              protocol: TCP
              containerPort: {{ include "split-host-port" .Values.server.extraArgs.opentsdbListenAddr }}
          {{- end }}
          {{- if .Values.server.extraArgs.opentsdbListenAddr }}
            - name: opentsdb-udp
              protocol: UDP
              containerPort: {{ include "split-host-port" .Values.server.extraArgs.opentsdbListenAddr }}
          {{- end }}
          {{- with $.Values.server.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.server.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.server.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- include "victoria-metrics.server.resources" . | nindent 12 }}
          securityContext:
            {{- $commonContainer.securityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: server-volume
              mountPath: {{ .Values.server.persistentVolume.mountPath }}
              subPath: {{ .Values.server.persistentVolume.subPath }}
          {{- if .Values.server.scrape.enabled }}
            - name: scrapeconfig
              mountPath: /scrapeconfig
          {{- end }}
          {{- range .Values.server.extraHostPathMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- range .Values.server.extraConfigmapMounts }}
            - name: {{ $.Values.server.name }}-{{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- range .Values.server.extraSecretMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- with .Values.server.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.global.backup.enabled }}
        - name: vmbackup
          image: {{ include "victoria-metrics.image.registry" (dict "image" .Values.backup.vmbackup.image "context" $) }}/{{ .Values.backup.vmbackup.image.repository }}:{{ .Values.backup.vmbackup.image.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - supercronic
          args:
            - -prometheus-listen-address
            - 0.0.0.0:{{ .Values.backup.supercronic.metrics.port }}
            - /app/crontab/vmbackup
          resources:
{{ toYaml .Values.backup.vmbackup.resources | indent 12 }}
          securityContext:
            {{- $commonContainer.securityContext | toYaml | nindent 12 }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.backup.awsSecrets .}}
                  key: accesskey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.backup.awsSecrets .}}
                  key: secretkey
          ports:
            - containerPort: {{ .Values.backup.supercronic.metrics.port }}
              name: supercronic
          volumeMounts:
            - mountPath: /storage
              name: server-volume
            - name: crontab
              mountPath: /app/crontab
            - mountPath: /app/crontab/scripts
              name: run-backup-script

        {{- end }}
        {{- if .Values.server.vmbackupmanager.enable }}
        - name: {{ template "victoria-metrics.name" . }}-vmbackupmanager
          image: {{ include "victoria-metrics.image.registry" (dict "image" .Values.server.vmbackupmanager.image "context" $) }}/{{ .Values.server.vmbackupmanager.image.repository }}:{{ .Values.server.vmbackupmanager.image.tag }}
          imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
          args:
            - {{ printf "%s=%t" "--eula" .Values.server.vmbackupmanager.eula | quote}}
            - {{ printf "%s=%t" "--disableHourly" .Values.server.vmbackupmanager.disableHourly | quote}}
            - {{ printf "%s=%t" "--disableDaily" .Values.server.vmbackupmanager.disableDaily | quote}}
            - {{ printf "%s=%t" "--disableWeekly" .Values.server.vmbackupmanager.disableWeekly | quote}}
            - {{ printf "%s=%t" "--disableMonthly" .Values.server.vmbackupmanager.disableMonthly | quote}}
            - {{ printf "%s=%d" "--keepLastHourly" (int .Values.server.vmbackupmanager.retention.keepLastHourly) | quote}}
            - {{ printf "%s=%d" "--keepLastDaily" (int .Values.server.vmbackupmanager.retention.keepLastDaily) | quote}}
            - {{ printf "%s=%d" "--keepLastWeekly" (int .Values.server.vmbackupmanager.retention.keepLastWeekly) | quote}}
            - {{ printf "%s=%d" "--keepLastMonthly" (int .Values.server.vmbackupmanager.retention.keepLastMonthly) | quote}}
            - {{ printf "%s=%s" "--dst" (printf "%s/%s" .Values.server.vmbackupmanager.destination (include "victoria-metrics.name" .) ) | quote}}
            - {{ printf "%s=%s" "--storageDataPath" .Values.server.persistentVolume.mountPath | quote}}
            - "--snapshot.createURL=http://localhost:8428/snapshot/create"
            - "--snapshot.deleteURL=http://localhost:8428/snapshot/delete"
            {{- range $key, $value := .Values.server.vmbackupmanager.extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          {{- with .Values.server.vmbackupmanager.resources }}
          resources: {{ toYaml . | nindent 12  }}
          {{- end }}
          securityContext:
            {{- $commonContainer.securityContext | toYaml | nindent 12 }}
          {{- with $.Values.server.vmbackupmanager.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.server.vmbackupmanager.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.vmbackupmanager.env }}
          env: {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: manager-http
              containerPort: 8300
          volumeMounts:
            - name: server-volume
              mountPath: {{ .Values.server.persistentVolume.mountPath }}
              subPath: {{ .Values.server.persistentVolume.subPath }}
          {{- with .Values.server.vmbackupmanager.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- with .Values.server.extraContainers }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
{{- include "victoria-metrics.image.pullSecret.name" (dict "images" (list .Values.server.image) "context" $) | indent 6 }}
    {{- if .Values.server.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.server.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.server.securityContext }}
      securityContext:
{{ toYaml .Values.server.securityContext | indent 8 }}
    {{- end }}
      serviceAccountName: {{ template "victoria-metrics.serviceAccountName" . }}
    {{- if .Values.server.tolerations }}
      tolerations:
{{ toYaml .Values.server.tolerations | indent 8 }}
    {{- end }}
    {{- $sizingAffinity := dict -}}
    {{- if contains "victoria-metrics-0" (include "victoria-metrics.server.fullname" .) -}}
      {{- $sizingAffinity = include "common.sizing.victoria-metrics-0.affinityConfig" . | fromYaml -}}
    {{- else if contains "victoria-metrics-1" (include "victoria-metrics.server.fullname" .) -}}
      {{- $sizingAffinity = include "common.sizing.victoria-metrics-1.affinityConfig" . | fromYaml -}}
    {{- end -}}
    {{- $finalAffinity := .Values.server.affinity | default dict -}}
    {{- if and (not .Values.server.affinity) $sizingAffinity -}}
      {{- $finalAffinity = $sizingAffinity -}}
    {{- end -}}
    {{- with $finalAffinity }}
      affinity: {{ toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.server.terminationGracePeriodSeconds }}
      volumes:
        {{- if .Values.server.scrape.enabled }}
        - name: scrapeconfig
          configMap:
            name: {{ include "victoria-metrics.server.scrape.configname" . }}
        {{- end }}
        {{- if not .Values.server.persistentVolume.enabled }}
        - name: server-volume
          emptyDir: {}
        {{- else }}
        {{- if .Values.server.persistentVolume.existingClaim }}
        - name: server-volume
          persistentVolumeClaim:
            claimName: {{ .Values.server.persistentVolume.existingClaim }}
        {{- end }}
        {{- end }}
        {{- if .Values.global.backup.enabled }}
        - name: crontab
          emptyDir: { }
        {{- end }}
        - name: run-backup-script
          configMap:
            name: {{ template "victoria-metrics.server.fullname" . }}-scripts
            defaultMode: 0755
        {{- with .Values.server.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  {{- if and .Values.server.persistentVolume.enabled (not .Values.server.persistentVolume.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: server-volume
        {{- if .Values.server.persistentVolume.annotations }}
        annotations:
{{ toYaml .Values.server.persistentVolume.annotations | indent 10 }}
        {{- end }}
      spec:
        accessModes:
{{ toYaml .Values.server.persistentVolume.accessModes | indent 10 }}
        resources:
          requests:
{{- $storageSize := include "common.sizing.victoria-metrics.storage" $ | trim -}}
{{- if $storageSize }}
            storage: "{{ $storageSize }}"
{{- else }}
            storage: "{{ .Values.server.persistentVolume.size }}"
{{- end }}
       {{ include "common.storage.class" ( dict "persistence" .Values.server.persistentVolume "global" .Values.global) | nindent 8 }}
      {{- with .Values.server.persistentVolume.matchLabels }}
        selector:
          matchLabels:
            {{- toYaml . | nindent 12 }}
      {{- end }}
{{- end }}
{{- end }}
