apiVersion: v2
appVersion: "6.0.0-snapshot.20240829112751-master-8082a57"
version: 1.11.5
description: Helm chart for StackState for Kubernetes
keywords:
  - kubernetes
  - observability
  - stackstate
home: https://gitlab.com/stackvista/stackstate.git
icon: https://www.stackstate.com/wp-content/uploads/2019/02/152x152-favicon.png
maintainers:
  - name: Stackstate Ops Team
    email: ops@stackstate.com
name: stackstate-k8s
dependencies:
  - name: anomaly-detection
    version: 5.2.0-snapshot.141
    repository: https://helm.stackstate.io
    condition: anomaly-detection.enabled
  - name: common
    repository: file://../common/
    version: "*"
  - name: elasticsearch
    condition: elasticsearch.enabled
    repository: file://../elasticsearch/
    # For some reason * does not work
    version: "8.11.4-stackstate.3"
  - name: hbase
    condition: hbase.enabled
    repository: file://../hbase/
    version: "0.2.35"
  - name: kafka
    condition: kafka.enabled
    # Bitnami official Helm repository stopped serving the old versions of the charts. This is the workaround https://github.com/bitnami/charts/issues/10539
    # repository: https://charts.bitnami.com/bitnami
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    version: 19.1.3
  - name: kafkaup-operator
    condition: kafkaup-operator.enabled
    repository: file://../kafkaup-operator/
    version: "*"
  - name: minio
    repository: file://../minio/
    # For some reason * does not work
    version: "8.0.10-stackstate.8"
    condition: backup.enabled
  - name: pull-secret
    version: "*"
    repository: file://../pull-secret/
    condition: pull-secret.enabled
  - name: zookeeper
    version: 8.1.2
    # Bitnami official Helm repository stopped serving the old versions of the charts. This is the workaround https://github.com/bitnami/charts/issues/10539
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: zookeeper.enabled
  - name: victoria-metrics-single
    alias: victoria-metrics-0
    version: "0.8.53-stackstate.6"
    repository: file://../victoria-metrics-single/
    condition: victoria-metrics-0.enabled
  - name: victoria-metrics-single
    alias: victoria-metrics-1
    version: "0.8.53-stackstate.6"
    repository: file://../victoria-metrics-single/
    condition: victoria-metrics-1.enabled
  - name: victoria-metrics-cluster
    repository: https://victoriametrics.github.io/helm-charts
    version: 0.11.20
    condition: victoria-metrics-cluster.enabled
  - name: clickhouse
    version: 3.6.9
    repository: https://charts.bitnami.com/bitnami
    condition: clickhouse.enabled
  - name: opentelemetry-collector
    version: 0.80.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry.enabled
