{
 "title": "StackState - Sync",
 "tags": [
  "stackstate",
  "sync"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(kube_service_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Sync - Average processing time for a synchronization message",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum by (integration_type, pod)(rate(stackstate_sync_duration_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m])) / (sum by (integration_type, pod)(rate(stackstate_sync_changes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))))",
     "legendFormat": "{{pod}} - {{integration_type}}"
    }
   ]
  },
  {
   "title": "Sync - Changes Rate",
   "type": "graph",
   "description": "Rate per second of the 1 minute average",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (integration_type, type, pod)(rate(stackstate_sync_changes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{pod}} - {{integration_type}} - {{type}}"
    }
   ]
  },
  {
   "title": "ExtTopo - conflated changes rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (integration_type, pod)(rate(stackstate_sync_extTopo_conflated_changes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{pod}} - {{integration_type}}"
    }
   ]
  },
  {
   "title": "ExtTopo - observed changes to conflate rate",
   "type": "graph",
   "description": "Rate per second of the 1 minute average",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (integration_type, pod)(rate(stackstate_sync_extTopo_observed_conflate_changes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{pod}} - {{integration_type}}"
    }
   ]
  },
  {
   "title": "Sync - Latency Seconds",
   "type": "graph",
   "description": "Time taken from collecting the data (in agent for example) until persisting in topology",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackstate_sync_latency_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.98\"}",
     "legendFormat": "{{pod}} - {{integration_type}}"
    }
   ]
  },
  {
   "title": "Sync - STS (Receiver to Sync) Latency Seconds",
   "type": "graph",
   "description": "Time taken from ingesting the data in STS (pushing to Kafka) until persisting in topology",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackstate_sync_sts_latency_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.98\"}",
     "legendFormat": "{{pod}} - {{integration_type}}"
    }
   ]
  },
  {
   "title": "Sync - Batch Errors Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (integration_type, pod)(rate(stackstate_sync_batch_errors_total{namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{pod}} - {{integration_type}}"
    }
   ]
  },
  {
   "title": "ExtTopo forwarded messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (integration_type, pod)(rate(stackstate_sync_extTopo_changes_forwarded_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{pod}} - {{integration_type}}"
    }
   ]
  },
  {
   "title": "ExtTopo deduplicated messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (integration_type, pod)(rate(stackstate_sync_extTopo_duplicated_changes_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{pod}} - {{integration_type}}"
    }
   ]
  }
 ]
}