{{- define "trafficmirror.service" -}}
spec:
  ports:
  - name: app
    port: 8080
    protocol: TCP
    targetPort: app
    {{- with .Values.service.appProtocol }}
    appProtocol: {{ . }}
    {{- end }}
{{- end -}}

{{- $commonService := fromYaml (include "common.service" .) -}}
{{- $trafficmirrorService := fromYaml (include "trafficmirror.service" .) -}}
{{- toYaml (merge $trafficmirrorService $commonService) -}}
