---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafkaup-operator.serviceaccount.fullname" . }}
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafkaup-operator.rolebinding.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kafkaup-operator.role.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kafkaup-operator.serviceaccount.fullname" . }}
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kafkaup-operator.role.fullname" . }}
rules:
- apiGroups: ["apps"]
  resources:
  - statefulsets
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list", "watch", "delete"]
