apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.fullname.short" . }}-stackstate-auth-secret
data:
  {{- if .Values.global.receiverApiKey }}
  receiver-api-key: {{ (printf "%s" .Values.global.receiverApiKey) | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.stackstate.authType "api-token" }}
    {{- if empty .Values.stackstate.apiToken -}}
      {{ fail "stackstate.apiToken is not set" }}
  stackstate-api-token: {{ (printf "%s" .Values.stackstate.apiToken) | b64enc | quote }}
    {{- end }}
  {{- end }}

  {{- if eq .Values.stackstate.authType "cookie" }}
    {{- if empty .Values.stackstate.username -}}
      {{ fail "stackstate.username is not set" }}
    {{- end }}
  stackstate-username: {{ (printf "%s" .Values.stackstate.username) | b64enc | quote }}
    {{- if empty .Values.stackstate.password -}}
      {{ fail "stackstate.password is not set" }}
    {{- end }}
  stackstate-password: {{ (printf "%s" .Values.stackstate.password) | b64enc | quote }}
  {{- end}}
type: Opaque
