apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "anomaly-detection.serviceaccount.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    stackstate.io/roles: stackstate-aad
{{- if .Values.image.pullSecretName }}
imagePullSecrets:
- name: {{ .Values.image.pullSecretName }}
{{- else if .Values.image.pullSecretUsername }}
imagePullSecrets:
- name: {{ include "anomaly-detection.pull.secret.fullname" . }}
{{- end }}
{{- if eq .Values.stackstate.authType "token" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "anomaly-detection.authentication.role.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["ping"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "anomaly-detection.authentication.rolebinding.fullname" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "anomaly-detection.serviceaccount.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "anomaly-detection.authentication.role.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- if (index .Values "cluster-role" "enabled") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "anomaly-detection.authentication.clusterrolebinding.fullname" . }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "anomaly-detection.serviceaccount.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
{{- end }}
{{- end }}
