{
 "title": "StackState - JVM",
 "tags": [
  "jvm",
  "stackstate"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "query": "label_values(kube_service_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\" }, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory heap",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "MemHeapMax",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "jvm_memory_bytes_max{area=\"heap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Max - {{pod}}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "MemHeapUsed",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "jvm_memory_bytes_used{area=\"heap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Used - {{pod}}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "MemHeapCommitted",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "jvm_memory_bytes_committed{area=\"heap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Commited - {{pod}}",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Memory non-heap",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "MemNonHeapMax",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "jvm_memory_bytes_max{area=\"nonheap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Max - {{pod}}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "MemNonHeapUsed",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "jvm_memory_bytes_used{area=\"nonheap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Used - {{pod}}",
     "precision": "default"
    },
    {
     "aggregator": "avg",
     "alias": "MemNonHeapCommitted",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Committed - {{pod}}",
     "precision": "default"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "GC / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m])",
     "legendFormat": "{{pod}} - {{gc}}"
    }
   ]
  },
  {
   "title": "Average GC duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m]) / rate(jvm_gc_collection_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[1m])",
     "legendFormat": "{{pod}} - {{gc}}"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Current - {{pod}}"
    },
    {
     "expr": "jvm_threads_peak{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Peak - {{pod}}"
    }
   ]
  },
  {
   "title": "JVM Deadlocked Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_deadlocked{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Deadlocked -{{pod}}"
    },
    {
     "expr": "jvm_threads_deadlocked_monitor{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "Deadlocked monitor - {{pod}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "Open - {{pod}}"
    },
    {
     "expr": "process_max_fds{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "Max - {{pod}}"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "Resident - {{pod}}"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=\"$namespace\", service=~\"$service\", pod=~\"$pod\"}",
     "legendFormat": "Virtual - {{pod}}"
    }
   ]
  }
 ]
}