
{{- define "stackstate.backup.stackgraph.container.init" }}
name: wait
command:
  - sh
  - -c
  - |
    /entrypoint -c {{ include "stackstate.minio.endpoint" . }},{{- if eq .Values.hbase.deployment.mode "Distributed" }}{{ include "stackstate.zookeeper.endpoint" . }},{{ .Release.Name }}-hbase-hdfs-nn-headful:9000{{- else -}}{{- .Release.Name }}-hbase-stackgraph:2182{{- end -}},{{ template "common.fullname.short" . }}-{{- if .Values.stackstate.experimental.server.split }}initializer:1618{{ else }}server-headless:7070{{ end }} -t 300
image: "{{include "stackstate.wait.image.registry" .}}/{{ .Values.stackstate.components.wait.image.repository }}:{{ .Values.stackstate.components.wait.image.tag }}"
imagePullPolicy: Always
{{- end }}
{{- define "stackstate.backup.stackgraph.container.main" }}
{{- $imageTagConfig := dict "ImageTag" .Values.stackstate.components.server.image.tag }}
name: backup-stackgraph
image: "{{ include "stackstate.image.registry" . }}/{{ .Values.stackstate.components.server.image.repository }}{{ .Values.stackstate.components.all.image.repositorySuffix }}:{{ include "stackstate.server.image.tag" (merge $imageTagConfig .) }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.server.image.pullPolicy | quote }}
command:
  - '/backup-restore-scripts/backup-stackgraph.sh'
env:
  {{- include "stackstate.backup.envvars" . | nindent 2 }}
  - name: ZOOKEEPER_QUORUM
    {{- if eq .Values.hbase.deployment.mode "Distributed" }}
    value: stackstate-zookeeper-headless:2181
    {{- else }}
    value: "stackstate-hbase-stackgraph:2182"
    {{- end }}
{{- with .Values.stackstate.components.backup.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
volumeMounts:
  {{- include "stackstate.backup.volumeMounts" . | nindent 2 }}
  - name: tmp-data
    mountPath: /tmp-data
{{- end }}

{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "stackstate.backup.stackgraph.container.main" .) -}}
{{- $stackgraphBackupMainContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideContainer := fromYaml (include "stackstate.backup.stackgraph.container.init" .) -}}
{{- $stackgraphBackupInitContainer := (merge $overrideContainer $commonContainer) -}}
{{- if .Values.backup.enabled }}
{{- if .Values.backup.stackGraph.scheduled.enabled }}
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ template "common.fullname.short" . }}-backup-sg
  labels:
    app.kubernetes.io/name: stackstate-k8s
    app.kubernetes.io/component: backup-stackgraph
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.backup.stackGraph.scheduled.schedule | quote }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: backup
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 600
      template:
        metadata:
          labels:
            app.kubernetes.io/component: backup
        spec:
          initContainers:
          - {{- toYaml $stackgraphBackupInitContainer | nindent 12 }}
          containers:
          - {{- toYaml $stackgraphBackupMainContainer | nindent 12 }}
          {{- include "stackstate.image.pullSecret.name" (dict "images" (list .Values.stackstate.components.all.image) "context" $) | nindent 10 }}
          volumes:
            {{- include "stackstate.backup.volumes" . | nindent 12 }}
            - name: tmp-data
              persistentVolumeClaim:
                claimName: {{ template "common.fullname.short" . }}-backup-stackgraph-tmp-data
        {{- if .Values.backup.stackGraph.securityContext.enabled }}
          securityContext: {{- omit .Values.backup.stackGraph.securityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
          restartPolicy: Never
{{- end }}

---
{{- end }}

{{- define "stackstate.backup.configuration.container.init" }}
name: wait
command:
  - sh
  - -c
  - |
    /entrypoint -c {{- if .Values.backup.enabled -}}{{ include "stackstate.minio.endpoint" . }},{{- end -}}{{- if eq .Values.hbase.deployment.mode "Distributed" }}{{ include "stackstate.zookeeper.endpoint" . }},{{ .Release.Name }}-hbase-hdfs-nn-headful:9000{{- else -}}{{- .Release.Name }}-hbase-stackgraph:2182{{- end -}},{{ template "common.fullname.short" . }}-{{- if .Values.stackstate.experimental.server.split }}initializer:1618{{ else }}server-headless:7070{{ end }} -t 300
image: "{{include "stackstate.wait.image.registry" .}}/{{ .Values.stackstate.components.wait.image.repository }}:{{ .Values.stackstate.components.wait.image.tag }}"
imagePullPolicy: Always
{{- end }}
{{- define "stackstate.backup.configuration.container.main" }}
{{- $imageTagConfig := dict "ImageTag" .Values.stackstate.components.server.image.tag }}
name: backup-settings
image: "{{ include "stackstate.image.registry" . }}/{{ .Values.stackstate.components.server.image.repository }}{{ .Values.stackstate.components.all.image.repositorySuffix }}:{{ include "stackstate.server.image.tag" (merge $imageTagConfig .) }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.server.image.pullPolicy | quote }}
command:
  - '/backup-restore-scripts/backup-configuration.sh'
env:
  {{- include "stackstate.backup.envvars" . | nindent 2 }}
  {{- include "stackstate.authentication.envvars" .  | nindent 2 }}
  {{- include "stackstate.baseurls.envvars" .  | nindent 2 }}
  - name: LICENSE_KEY
    valueFrom:
      secretKeyRef:
        name: {{ template "common.fullname.short" . }}-license
        key: sts-license-key
  {{ if .Values.backup.configuration.yaml.maxSizeLimit }}
  - name: CONFIG_FORCE_stackstate_yaml_codePointLimit
    value: "{{ include "stackstate.backup.yaml.maxSizeLimit" . }}"
  {{ end }}
  - name: PROMETHEUS_WRITE_ENDPOINT
    value: http://{{ include "stackstate.vmagent.endpoint" . }}:8429/api/v1/write
  - name: HADOOP_USER_NAME
    value: nobody
  - name: ZOOKEEPER_QUORUM
    {{- if eq .Values.hbase.deployment.mode "Distributed" }}
    value: stackstate-zookeeper-headless:2181
    {{- else }}
    value: "stackstate-hbase-stackgraph:2182"
    {{- end }}
  {{- include "stackstate.component.envsFromExistingSecrets" .Values.stackstate.components.all.envsFromExistingSecrets }}
{{- with .Values.stackstate.components.configurationBackup.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
volumeMounts:
  {{- include "stackstate.backup.volumeMounts" . | nindent 2 }}
  - name: settings-backup-data
    mountPath: /settings-backup-data
{{- end }}

{{- if .Values.backup.configuration.scheduled.enabled }}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "stackstate.backup.configuration.container.main" .) -}}
{{- $configBackupMainContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideContainer := fromYaml (include "stackstate.backup.configuration.container.init" .) -}}
{{- $configBackupInitContainer := (merge $overrideContainer $commonContainer) -}}
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ template "common.fullname.short" . }}-backup-conf
  labels:
    app.kubernetes.io/name: stackstate-k8s
    app.kubernetes.io/component: backup-settings
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.backup.configuration.scheduled.schedule | quote }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: backup
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 600
      template:
        metadata:
          labels:
            app.kubernetes.io/component: backup
        spec:
          initContainers:
          - {{- toYaml $configBackupInitContainer | nindent 12 }}
          containers:
          - {{- toYaml $configBackupMainContainer | nindent 12 }}
          {{- include "stackstate.image.pullSecret.name" (dict "images" (list .Values.stackstate.components.all.image) "context" $) | nindent 10 }}
          # Specifically setting this to empty string to unset previously used service account https://github.com/helm/helm/issues/10183
          serviceAccount: ""
          serviceAccountName: ""
          volumes:
            {{- include "stackstate.backup.volumes" . | nindent 12 }}
            - name: settings-backup-data
              persistentVolumeClaim:
                claimName: {{ template "common.fullname.short" . }}-settings-backup-data
        {{- if .Values.backup.configuration.securityContext.enabled }}
          securityContext: {{- omit .Values.backup.stackGraph.securityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
          restartPolicy: Never
{{- end }}
