{
 "title": "StackState - Kafka2Es",
 "tags": [
  "stackstate",
  "kafka2es"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(kube_service_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka2Es - Data Latency (from source to being persisted)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackstate_kafka2es_data_latency_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{data_type}} - {{service}}"
    }
   ]
  },
  {
   "title": "Kafka2Es - Kafka Messages consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by(data_type, service)(rate(stackstate_kafka2es_data_latency_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{data_type}} - {{service}}"
    }
   ]
  },
  {
   "title": "Kafka2Es - Data Latency (from received to being persisted)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackstate_kafka2es_received_data_latency_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{data_type}} - {{service}}"
    }
   ]
  },
  {
   "title": "Kafka2Es - Time to catch up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(data_type, service)(stackstate_kafka2es_received_data_latency_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.95\"}) / sum by(data_type, service)(rate(stackstate_kafka2es_received_data_latency_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{data_type}} - {{service}}"
    }
   ]
  },
  {
   "title": "Kafka2Es - GenericEvent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (index_name)(stackstate_kafka2es_index_capacity_quota_bytes{data_type=\"GenericEvent\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "{{index_name}} - Quotum"
    },
    {
     "expr": "max by (index_name)(stackstate_kafka2es_index_capacity_usage_bytes{data_type=\"GenericEvent\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "{{index_name}} - Used"
    }
   ]
  },
  {
   "title": "Kafka2Es - TopologyEvent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (index_name)(stackstate_kafka2es_index_capacity_quota_bytes{data_type=\"TopologyEvent\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "{{index_name}} - Quotum"
    },
    {
     "expr": "max by (index_name)(stackstate_kafka2es_index_capacity_usage_bytes{data_type=\"TopologyEvent\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "{{index_name}} - Used"
    }
   ]
  },
  {
   "title": "Kafka2Es - StsEvent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (index_name)(stackstate_kafka2es_index_capacity_quota_bytes{data_type=\"StsEvent\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "{{index_name}} - Quotum"
    },
    {
     "expr": "max by (index_name)(stackstate_kafka2es_index_capacity_usage_bytes{data_type=\"StsEvent\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "{{index_name}} - Used"
    }
   ]
  },
  {
   "title": "Kafka2Es - MultiMetric",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (index_name)(stackstate_kafka2es_index_capacity_quota_bytes{data_type=\"MultiMetric\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "{{index_name}} - Quotum"
    },
    {
     "expr": "max by (index_name)(stackstate_kafka2es_index_capacity_usage_bytes{data_type=\"MultiMetric\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "{{index_name}} - Used"
    }
   ]
  },
  {
   "title": "Kafka2Es - Trace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (index_name)(stackstate_kafka2es_index_capacity_quota_bytes{data_type=\"Trace\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "{{index_name}} - Quotum"
    },
    {
     "expr": "max by (index_name)(stackstate_kafka2es_index_capacity_usage_bytes{data_type=\"Trace\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "{{index_name}} - Used"
    }
   ]
  }
 ]
}