{{- define "stackstate.sync.configmap-log" -}}
metadata:
  name: {{ template "common.fullname.short" . }}-sync-log
data:
  logback.xml: |
{{- $logging := printf "%s\n%s" (include "stackstate.configmap.server-base-log" .) (include "stackstate.configmap.sync-log" .) .Values.stackstate.components.sync.additionalLogging -}}
{{- include "stackstate.configmap.microservices-log" (merge (dict "RootLevel" "WARN" "AdditionalLogging" $logging) .) | nindent 4 -}}
{{- end -}}

{{- if .Values.stackstate.experimental.server.split }}
{{- $commonConfigMap := fromYaml (include "common.configmap" .) -}}
{{- $stackstateSyncLogConfigMap := fromYaml (include "stackstate.sync.configmap-log" .) -}}
{{- toYaml (merge $stackstateSyncLogConfigMap $commonConfigMap) -}}
{{- end -}}
