
{{- define "stackstate.backup.stackgraph.container.init" }}
name: wait
command:
  - sh
  - -c
  - |
    /entrypoint -c {{ include "stackstate.minio.endpoint" . }},{{ include "stackgraph.hbase.waitfor" . }},{{ template "common.fullname.short" . }}-{{- if include "suse-observability.features.enabled" (dict "key" "server.split" "context" .) }}initializer:1618{{ else }}server-headless:7070{{ end }} -t 300
image: "{{include "stackstate.wait.image.registry" .}}/{{ .Values.stackstate.components.wait.image.repository }}:{{ .Values.stackstate.components.wait.image.tag }}"
imagePullPolicy: Always
{{- end }}
{{- define "stackstate.backup.stackgraph.container.main" }}
{{- $imageTagConfig := dict "ImageTag" .Values.stackstate.components.server.image.tag }}
name: backup-stackgraph
image: "{{ include "stackstate.image.registry" . }}/{{ .Values.stackstate.components.server.image.repository }}{{ .Values.stackstate.components.all.image.repositorySuffix }}:{{ include "stackstate.server.image.tag" (merge $imageTagConfig .) }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.server.image.pullPolicy | quote }}
command:
  - '/backup-restore-scripts/backup-stackgraph.sh'
env:
  {{- include "stackstate.backup.envvars" . | nindent 2 }}
  - name: ZOOKEEPER_QUORUM
    value: {{ include "stackgraph.zookeeper.endpoint" . | quote }}
{{- with .Values.stackstate.components.backup.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
volumeMounts:
  {{- include "stackstate.backup.volumeMounts" . | nindent 2 }}
  - name: tmp-data
    mountPath: /tmp-data
{{- end }}

{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "stackstate.backup.stackgraph.container.main" .) -}}
{{- $stackgraphBackupMainContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideInitContainer := fromYaml (include "stackstate.backup.stackgraph.container.init" .) -}}
{{- $stackgraphBackupInitContainer := (merge $overrideInitContainer $commonContainer) -}}
{{- if .Values.global.backup.enabled }}
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ template "common.fullname.short" . }}-backup-sg
  labels:
    app.kubernetes.io/name: suse-observability
    app.kubernetes.io/component: backup-sg
    {{- include "suse-observability.labels.global" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.backup.stackGraph.scheduled.schedule | quote }}
  {{- if .Values.deployment.compatibleWithArgoCD }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: backup
        {{- include "suse-observability.labels.global" . | nindent 8 }}
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: {{ include "stackstate.job.ttlSecondsAfterFinished" . }}
      template:
        metadata:
        {{- if or .Values.stackstate.components.all.podAnnotations .Values.stackstate.components.backup.podAnnotations }}
          annotations:
          {{- with .Values.stackstate.components.all.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.stackstate.components.backup.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
          labels:
            app.kubernetes.io/component: backup
            {{- include "suse-observability.labels.global" . | nindent 12 }}
          {{- with .Values.stackstate.components.backup.podLabels }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          initContainers:
          - {{- toYaml $stackgraphBackupInitContainer | nindent 12 }}
          containers:
          - {{- toYaml $stackgraphBackupMainContainer | nindent 12 }}
          {{- include "stackstate.image.pullSecret.name" (dict "context" $) | nindent 10 }}
          volumes:
            {{- include "stackstate.backup.volumes" . | nindent 12 }}
            - name: tmp-data
              persistentVolumeClaim:
                claimName: {{ template "common.fullname.short" . }}-backup-stackgraph-tmp-data
        {{- if or .Values.stackstate.components.all.nodeSelector .Values.stackstate.components.backup.nodeSelector }}
          nodeSelector:
          {{- with .Values.stackstate.components.all.nodeSelector }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.stackstate.components.backup.nodeSelector }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if or .Values.stackstate.components.all.affinity .Values.stackstate.components.backup.affinity }}
          affinity:
          {{- with .Values.stackstate.components.all.affinity }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.stackstate.components.backup.affinity }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if or .Values.stackstate.components.all.tolerations .Values.stackstate.components.backup.tolerations }}
          tolerations:
          {{- with .Values.stackstate.components.all.tolerations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.stackstate.components.backup.tolerations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .Values.backup.stackGraph.securityContext.enabled }}
          securityContext: {{- omit .Values.backup.stackGraph.securityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
          restartPolicy: Never
---
{{- end }}

{{- define "stackstate.backup.configuration.container.init" }}
name: wait
command:
  - sh
  - -c
  - |
    /entrypoint -c {{- if .Values.global.backup.enabled -}}{{ include "stackstate.minio.endpoint" . }},{{- end -}}{{ include "stackgraph.hbase.waitfor" . }},{{ template "common.fullname.short" . }}-{{- if include "suse-observability.features.enabled" (dict "key" "server.split" "context" .) }}initializer:1618{{ else }}server-headless:7070{{ end }} -t 300
image: "{{include "stackstate.wait.image.registry" .}}/{{ .Values.stackstate.components.wait.image.repository }}:{{ .Values.stackstate.components.wait.image.tag }}"
imagePullPolicy: Always
{{- end }}
{{- define "stackstate.backup.configuration.container.main" }}
{{- $imageTagConfig := dict "ImageTag" .Values.stackstate.components.server.image.tag }}
name: backup-settings
image: "{{ include "stackstate.image.registry" . }}/{{ .Values.stackstate.components.server.image.repository }}{{ .Values.stackstate.components.all.image.repositorySuffix }}:{{ include "stackstate.server.image.tag" (merge $imageTagConfig .) }}"
imagePullPolicy: {{ default .Values.stackstate.components.all.image.pullPolicy .Values.stackstate.components.server.image.pullPolicy | quote }}
command:
  - '/backup-restore-scripts/backup-configuration.sh'
envFrom:
  - secretRef:
      name: {{ include "stackstate.secret.name.license" .  }}
env:
  {{- include "stackstate.backup.envvars" . | nindent 2 }}
  {{- include "stackstate.baseurls.envvars" .  | nindent 2 }}
  {{ if .Values.backup.configuration.yaml.maxSizeLimit }}
  - name: CONFIG_FORCE_stackstate_yaml_codePointLimit
    value: "{{ include "stackstate.backup.yaml.maxSizeLimit" . }}"
  {{ end }}
  - name: PROMETHEUS_WRITE_ENDPOINT
    value: http://{{ include "stackstate.vmagent.endpoint" . }}:8429/api/v1/write
  - name: HADOOP_USER_NAME
    value: nobody
  - name: ZOOKEEPER_QUORUM
    value: {{ include "stackgraph.zookeeper.endpoint" . | quote }}
  {{- include "stackstate.component.envsFromExistingSecrets" .Values.stackstate.components.all.envsFromExistingSecrets }}
{{- with .Values.stackstate.components.configurationBackup.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
volumeMounts:
  {{- include "stackstate.backup.volumeMounts" . | nindent 2 }}
  - name: settings-backup-data
    mountPath: /settings-backup-data
{{- end }}

{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "stackstate.backup.configuration.container.main" .) -}}
{{- $configBackupMainContainer := (merge $overrideContainer $commonContainer) -}}
{{- $overrideInitContainer := fromYaml (include "stackstate.backup.configuration.container.init" .) -}}
{{- $configBackupInitContainer := (merge $overrideInitContainer $commonContainer) -}}
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ template "common.fullname.short" . }}-backup-conf
  labels:
    app.kubernetes.io/name: suse-observability
    app.kubernetes.io/component: backup-settings
    {{- include "suse-observability.labels.global" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.backup.configuration.scheduled.schedule | quote }}
  {{- if .Values.deployment.compatibleWithArgoCD }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: backup
        {{- include "suse-observability.labels.global" . | nindent 8 }}
    spec:
      backoffLimit: 1
      {{- if not .Values.deployment.compatibleWithArgoCD }}
      ttlSecondsAfterFinished: {{ include "stackstate.job.ttlSecondsAfterFinished" . }}
      {{- end }}
      template:
        metadata:
        {{- if or .Values.stackstate.components.all.podAnnotations .Values.stackstate.components.configurationBackup.podAnnotations }}
          annotations:
          {{- with .Values.stackstate.components.all.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.stackstate.components.configurationBackup.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
          labels:
            app.kubernetes.io/component: backup
            {{- include "suse-observability.labels.global" . | nindent 12 }}
          {{- with .Values.stackstate.components.configurationBackup.podLabels }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          initContainers:
          - {{- toYaml $configBackupInitContainer | nindent 12 }}
          containers:
          - {{- toYaml $configBackupMainContainer | nindent 12 }}
          {{- include "stackstate.image.pullSecret.name" (dict "context" $) | nindent 10 }}
          # Specifically setting this to empty string to unset previously used service account https://github.com/helm/helm/issues/10183
          serviceAccount: ""
          serviceAccountName: ""
          volumes:
            {{- include "stackstate.backup.volumes" . | nindent 12 }}
            - name: settings-backup-data
              persistentVolumeClaim:
                claimName: {{ template "common.fullname.short" . }}-settings-backup-data
        {{- if or .Values.stackstate.components.all.nodeSelector .Values.stackstate.components.configurationBackup.nodeSelector }}
          nodeSelector:
          {{- with .Values.stackstate.components.all.nodeSelector }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.stackstate.components.configurationBackup.nodeSelector }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if or .Values.stackstate.components.all.affinity .Values.stackstate.components.configurationBackup.affinity }}
          affinity:
          {{- with .Values.stackstate.components.all.affinity }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.stackstate.components.configurationBackup.affinity }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if or .Values.stackstate.components.all.tolerations .Values.stackstate.components.configurationBackup.tolerations }}
          tolerations:
          {{- with .Values.stackstate.components.all.tolerations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.stackstate.components.configurationBackup.tolerations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .Values.backup.configuration.securityContext.enabled }}
          securityContext: {{- omit .Values.backup.stackGraph.securityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
          restartPolicy: Never
