{{- if .Values.global.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "common.fullname.short" . }}-backup-init
  labels:
    app.kubernetes.io/component: backup
    {{- include "suse-observability.labels.global" . | nindent 4 }}
spec:
  schedule: "0 0 31 2 *"
  suspend: true
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: backup
        {{- include "suse-observability.labels.global" . | nindent 8 }}
    spec:
      {{- include "suse-observability.backup.init.jobSpec" . | nindent 6 }}
{{- end }}
