{{- if .Values.gateway.enabled -}}
{{- $routerName := (include "stackstate.router.name" .) -}}
{{- $baseUrl := include "suse-observability.global.baseUrl" . | trim -}}
{{- $baseUrlHost := "" -}}
{{- $baseUrlPath := "" -}}
{{- if $baseUrl -}}
  {{- $baseUrlHost = (urlParse $baseUrl).host -}}
  {{- $baseUrlPath = (urlParse $baseUrl).path -}}
{{- end -}}
{{- $hostnames := .Values.gateway.hostnames | default (list $baseUrlHost) -}}
{{- $pathPrefix := .Values.gateway.path | default $baseUrlPath | default "/" -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "stackstate.hostname.prefix" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- range .Values.gateway.parentRefs }}
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
      {{- if .port }}
      port: {{ .port }}
      {{- end }}
    {{- end }}
  hostnames:
    {{- range $hostnames }}
    - {{ tpl . $ | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ $pathPrefix | quote }}
      backendRefs:
        - name: {{ $routerName }}
          port: 8080
          {{- if .Values.gateway.backendWeight }}
          weight: {{ .Values.gateway.backendWeight }}
          {{- end }}
      {{- if .Values.gateway.filters }}
      filters:
        {{- toYaml .Values.gateway.filters | nindent 8 }}
      {{- end }}
      {{- if .Values.gateway.timeouts }}
      timeouts:
        {{- toYaml .Values.gateway.timeouts | nindent 8 }}
      {{- end }}
{{- end }}
