{{- define "stackstate.clickhouseCleanup.job.initContainer.main" -}}
{{- $replicaCount := include "common.sizing.clickhouse.effectiveReplicaCount" . | int -}}
{{- $hostList := list -}}
{{- range $i, $e := reverse (until $replicaCount) -}}
{{- $hostList = append $hostList (printf "%s-shard0-%d.%s-headless.%s.svc.cluster.local:8123" $.Values.clickhouse.fullnameOverride  $e $.Values.clickhouse.fullnameOverride $.Release.Namespace) -}}
{{- end -}}
name: clickhouse-cleanup-init
command:
- sh
- -c
- |
  /entrypoint -c {{ join "," $hostList }} -t 1800
image: "{{ include "stackstate.wait.image.registry" . }}/{{ .Values.global.wait.image.repository }}:{{ .Values.global.wait.image.tag }}"
imagePullPolicy: {{ .Values.global.wait.image.pullPolicy | quote }}
{{- end }}
{{- define "stackstate.clickhouseCleanup.job.container.main" -}}
{{- $replicaCount := include "common.sizing.clickhouse.effectiveReplicaCount" . -}}
command:
- bash
- -c
- |
  {{ .Files.Get "scripts/job-clickhouse-cleanup.sh" | nindent 2 }}
env:
- name: USERNAME
  value: {{ .Values.clickhouse.auth.username | quote }}
- name: PASSWORD
  value: {{ .Values.clickhouse.auth.password | quote }}
- name: CLICKHOUSE_HOST_PREFIX
  value: {{ .Values.clickhouse.fullnameOverride | quote }}
- name: CLICKHOUSE_REPLICA_COUNT
  value: {{ $replicaCount | quote }}
- name: NAMESPACE
  value: {{ .Release.Namespace | quote }}
{{- if .Values.stackstate.components.clickhouseCleanup.extraEnv.open }}
  {{- range $key, $value := .Values.stackstate.components.clickhouseCleanup.extraEnv.open  }}
- name: {{ $key }}
  value: {{ $value | quote }}
  {{- end }}
{{- end }}
image: "{{include "stackstate.clickhouseCleanup.image.registry" .}}/{{ .Values.stackstate.components.clickhouseCleanup.image.repository }}:{{ .Values.stackstate.components.clickhouseCleanup.image.tag }}"
imagePullPolicy: {{ .Values.stackstate.components.clickhouseCleanup.image.pullPolicy | quote }}
name: clickhouse-cleanup
{{- with .Values.stackstate.components.clickhouseCleanup.resources }}
resources:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}

{{- define "stackstate.clickhouseCleanup.job" -}}
{{- $commonContainer := fromYaml (include "common.container" .) -}}
{{- $overrideContainer := fromYaml (include "stackstate.clickhouseCleanup.job.container.main" .) -}}
{{- $stsstackstateclickhouseCleanupMainContainer := (merge $overrideContainer $commonContainer) -}}
apiVersion: batch/v1
kind: Job
metadata:
  {{- if .Values.deployment.compatibleWithArgoCD }}
  generateName: ch-clean
  {{- else }}
  name: {{ template "common.fullname.short" . }}-ch-clean{{ now | date "02t150405" }}
  {{- end }}
  labels:
    app.kubernetes.io/component: ch-clean
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- include "suse-observability.labels.global" . | nindent 4 }}
  annotations:
    {{- if .Values.deployment.compatibleWithArgoCD }}
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    {{- else }}
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- end }}
  {{- with .Values.stackstate.components.clickhouseCleanup.jobAnnotations }}
    {{- toYaml . | nindent 4}}
  {{- end }}
spec:
  backoffLimit: 20
  ttlSecondsAfterFinished: {{ include "stackstate.job.ttlSecondsAfterFinished" . }}
  template:
    metadata:
      annotations:
        {{- include "stackstate.common.secret.checksum" . | nindent 8 }}
        {{- include "stackstate.server.secret.checksum" . | nindent 8 }}
      {{- with .Values.stackstate.components.all.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.clickhouseCleanup.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: ch-clean
        {{- include "suse-observability.labels.global" . | nindent 8 }}
      {{- with .Values.stackstate.components.clickhouseCleanup.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: OnFailure
      initContainers:
      - {{ include "stackstate.clickhouseCleanup.job.initContainer.main" . | nindent 8 }}
      containers:
      - {{ toYaml $stsstackstateclickhouseCleanupMainContainer | nindent 8 }}
      {{- include "stackstate.image.pullSecret.name" (dict "context" $) | nindent 6 }}
    {{- if or .Values.stackstate.components.all.nodeSelector .Values.stackstate.components.clickhouseCleanup.nodeSelector }}
      nodeSelector:
      {{- with .Values.stackstate.components.all.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.clickhouseCleanup.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.affinity .Values.stackstate.components.clickhouseCleanup.affinity }}
      affinity:
      {{- with .Values.stackstate.components.all.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.clickhouseCleanup.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or .Values.stackstate.components.all.tolerations .Values.stackstate.components.clickhouseCleanup.tolerations }}
      tolerations:
      {{- with .Values.stackstate.components.all.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stackstate.components.clickhouseCleanup.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if .Values.stackstate.components.clickhouseCleanup.securityContext.enabled }}
      securityContext: {{- omit .Values.stackstate.components.clickhouseCleanup.securityContext "enabled" | toYaml | nindent 8 }}
    {{- end }}
{{- end -}}

{{ include "stackstate.clickhouseCleanup.job" . }}
