{{- if .Values.global.backup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname.short" . }}-backup-stackgraph-tmp-data
  annotations:
    monitor.kubernetes-v2.stackstate.io/pvc-orphan: |-
      {
        "enabled": false
      }
spec:
  accessModes: {{ .Values.backup.stackGraph.scheduled.tempData.accessModes }}
  resources:
    requests:
{{- $deploymentMode := include "suse-observability.hbase.deploymentMode" . -}}
      {{- if eq $deploymentMode "Distributed" }}
      storage: {{ .Values.backup.stackGraph.scheduled.tempData.size | default .Values.hbase.hdfs.datanode.persistence.size }}
      {{- else}}
      storage: {{ .Values.backup.stackGraph.scheduled.tempData.size | default .Values.hbase.stackgraph.persistence.size }}
      {{- end }}
  {{ include "common.storage.class" ( dict "persistence" .Values.backup.stackGraph.scheduled.tempData "global" .Values.global) | nindent 2 }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname.short" . }}-settings-backup-data
  annotations:
    monitor.kubernetes-v2.stackstate.io/pvc-orphan: |-
      {
        "enabled": false
      }
spec:
  accessModes: {{ .Values.backup.stackGraph.scheduled.tempData.accessModes }}
  resources:
    requests:
      storage: {{ tpl .Values.backup.configuration.scheduled.pvc.size . }}
  {{ include "common.storage.class" ( dict "persistence" .Values.backup.configuration.scheduled.pvc "global" .Values.global) | nindent 2 }}
