{{- if and (include "suse-observability.features.enabled" (dict "key" "storeTransactionLogsToPVC.enabled" "context" .)) (include "suse-observability.features.enabled" (dict "key" "server.split" "context" .)) }}
{{- $storageClass := include "suse-observability.features.get" (dict "key" "storeTransactionLogsToPVC.storageClass" "context" . ) | trim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname.short" . }}-checks-txlog
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- include "common.labels.custom" . | nindent 4 }}
{{- if .Values.gitlab }}
  annotations:
    {{- include "common.annotations.gitlab" . | nindent 4 }}
{{- end }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ include "suse-observability.features.get" (dict "key" "storeTransactionLogsToPVC.volumeSize" "context" . ) | trim }}
{{- if and $storageClass (ne $storageClass "<no value>") }}
  storageClassName: {{ $storageClass }}
{{- end }}
{{- end -}}

{{- if and .Values.stackstate.components.checks.tmpToPVC (include "suse-observability.features.enabled" (dict "key" "server.split" "context" .)) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname.short" . }}-checks-tmp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.stackstate.components.checks.tmpToPVC.volumeSize }}
  {{ include "common.storage.class" ( dict "persistence" .Values.stackstate.components.checks.tmpToPVC "global" .Values.global) | nindent 2 }}
{{- end}}
