{{- if include "suse-observability.global.hasPullSecret" . -}}
{{- $imageRegistry := include "suse-observability.global.imageRegistry" . | default "quay.io" -}}
{{- $username := .Values.global.suseObservability.pullSecret.username -}}
{{- $password := .Values.global.suseObservability.pullSecret.password -}}
{{- $authMessage := printf "%s:%s" $username $password | b64enc -}}
{{- $registryAuthDocument := dict "auth" $authMessage -}}
{{- $auths := dict $imageRegistry $registryAuthDocument -}}
{{- $dockerConfigJson := dict "auths" $auths -}}
apiVersion: v1
kind: Secret
metadata:
  # This secret has exactly the same name as the normal pull secret but gets created at pre-install and post-delete hooks
  # for use in other pre-install and post-delete hooks.
  name: suse-observability-pull-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: suse-observability
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "-1000"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
data:
  .dockerconfigjson: {{ $dockerConfigJson | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}
