{{- /*
    The K8s service for the Clickhouse backup
*/ -}}
{{- define "stackstate.backup.clickhouse.backup.service" -}}
suse-observability-clickhouse-backup
{{- end -}}

{{- define "stackstate.clickhouse-backup.service" -}}
apiVersion: {{ .Values.common.service.apiVersion }}
kind: Service
metadata:
  name: {{ include "stackstate.backup.clickhouse.backup.service" . }}
  labels:
    app.kubernetes.io/component: clickhouse-backup
spec:
  clusterIP: None
  ports:
    - name: backup-api
      port: 7171
      protocol: TCP
      targetPort: backup-api
    - name: tcp
      port: 9000
      protocol: TCP
      targetPort: tcp
  selector:
    app.kubernetes.io/component: clickhouse
    shard: "0"
    statefulset.kubernetes.io/pod-name: "suse-observability-clickhouse-shard0-0"
  type: ClusterIP
{{- end -}}

{{- if .Values.global.backup.enabled }}
{{- include "stackstate.clickhouse-backup.service" . -}}
{{- end -}}
