{{- if and .Values.global.features.experimentalOtelLogsAgent .Values.otelLogsAgent.enabled }}
{{- $image := .Values.otelLogsAgent.image }}
{{- include "stackstate-k8s-agent.logsAgent.validate" . }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-logs-agent
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "stackstate-k8s-agent.labels" . | indent 4 }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 4 }}
    app.kubernetes.io/component: logs-agent
  annotations:
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: logs-agent
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "stackstate-k8s-agent.name" . }}
{{- with .Values.otelLogsAgent.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
{{- end }}
  template:
    metadata:
      annotations:
        ad.stackstate.com/logs-agent.check_names: '["openmetrics"]'
        ad.stackstate.com/logs-agent.init_configs: '[{}]'
        ad.stackstate.com/logs-agent.instances: '[{"prometheus_url":"http://%%host%%:8888/metrics","namespace":"stackstate","metrics":["*"]}]'
        {{- include "stackstate-k8s-agent.checksum-configs" . | nindent 8 }}
        {{- include "stackstate-k8s-agent.logsAgent.configmap.override.checksum" . | nindent 8 }}
        {{- include "stackstate-k8s-agent.customCertificates.checksum" . | nindent 8 }}
{{ include "stackstate-k8s-agent.global.extraAnnotations" . | indent 8 }}
      {{- with .Values.otelLogsAgent.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: logs-agent
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "stackstate-k8s-agent.name" . }}
{{ include "stackstate-k8s-agent.global.extraLabels" . | indent 8 }}
      {{- with .Values.otelLogsAgent.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "stackstate-k8s-agent.image.pullSecrets" (dict "images" (list $image .Values.all.image) "context" $) | nindent 6 }}
      terminationGracePeriodSeconds: 120
      containers:
        - name: logs-agent
          image: "{{ include "stackstate-k8s-agent.imageRegistry" . }}/{{ $image.repository }}:{{ $image.tag }}"
          args:
          - --config=/etc/otel/otel-logs.yaml
          - --feature-gates=stanza.synchronousLogEmitter
          imagePullPolicy: "{{ $image.pullPolicy }}"
          env:
          {{ include "stackstate-k8s-agent.apiKeyEnv" . | nindent 10 }}
          {{- include "stackstate-k8s-agent.platformUrlEnv" . | nindent 10 }}
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: PROMTAIL_LOGS_URL
            {{- if .Values.global.url.fromSecret }}
            value: "$(STS_URL)/logs/k8s"
            {{- else }}
            value: {{ printf "%s/logs/k8s" (tpl .Values.stackstate.url . | trimAll "/") | quote }}
            {{- end }}
          - name: CLUSTER_NAME
            {{- include "stackstate-k8s-agent.clusterNameEnvValue" . | nindent 12 }}
          - name: PROXY_URL
            value: {{ .Values.global.proxy.url | default "" | quote }}
          securityContext:
            seLinuxOptions:
              type: spc_t
            privileged: false
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
          ports:
            - name: health
              containerPort: 13133
            - name: metrics
              containerPort: 8888
          startupProbe:
            httpGet:
              path: /live
              port: health
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /live
              port: health
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: health
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 1
        {{- with .Values.otelLogsAgent.resources }}
          resources:
            {{- toYaml (omit . "override") | nindent 12 }}
        {{- end }}
          volumeMounts:
            - name: logs
              mountPath: /var/log
              readOnly: true
            - name: logs-agent-config
              mountPath: /etc/otel
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: logs-agent-state
              mountPath: /var/lib/otelcol
          {{- include "stackstate-k8s-agent.customCertificates.volumeMount" . | nindent 12 }}
      {{- if .Values.otelLogsAgent.priorityClassName }}
      priorityClassName: {{ .Values.otelLogsAgent.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-logs-agent
    {{- with .Values.otelLogsAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.otelLogsAgent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.otelLogsAgent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: logs
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: logs-agent-config
          configMap:
            name: {{ .Release.Name }}-logs-agent
        - name: logs-agent-state
          emptyDir: {}
      {{- include "stackstate-k8s-agent.customCertificates.volume" . | nindent 8 }}
{{- end -}}
