{{- if .Values.podSecurityPolicies.enabled -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ include "elasticsearch-exporter.role.fullname" . }}
  labels:
    chart: {{ template "elasticsearch-exporter.chart" . }}
    app: {{ template "elasticsearch-exporter.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ include "elasticsearch-exporter.podsecuritypolicy.fullname" . }}
{{- end }}
