annotations:
  category: Database
  images: |
    - name: clickhouse
      image: docker.io/bitnami/clickhouse:23.7.4-debian-11-r5
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r40
  licenses: Apache-2.0
apiVersion: v2
appVersion: 23.7.4
dependencies:
  - name: common
    repository: file://charts/common
    tags:
      - bitnami-common
    version: 2.x.x
  - name: suse-observability-sizing
    repository: file://../suse-observability-sizing
    version: 0.1.2
description:
  ClickHouse is an open-source column-oriented OLAP database management
  system. Use it to boost your database performance while providing linear scalability
  and hardware efficiency.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/clickhouse/img/clickhouse-stack-220x234.png
keywords:
  - database
  - sharding
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: clickhouse
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/clickhouse
version: 3.6.9-suse-observability.8
