{
 "title": "StackState - Overview",
 "description": "Look here for a high level overview of StackState load and performance",
 "tags": [
  "stackstate",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(kube_service_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Elasticserach Metric / Event / Trace ingestion latency",
   "type": "row",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Kafka2Es - Data Latency (from received to being persisted)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackstate_kafka2es_received_data_latency_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.95\"}",
     "legendFormat": "{{data_type}} - {{service}}"
    }
   ]
  },
  {
   "title": "Kafka2Es - Time to catch up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "stackstate_kafka2es_received_data_latency_seconds{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", quantile=\"0.95\"} / sum by(data_type, service)(rate(stackstate_kafka2es_received_data_latency_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{data_type}} - {{service}}"
    }
   ]
  },
  { "title": "Kafka topic record consumption", "type": "row", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 } },
  {
   "title": "Kafka - Topic record consumption - lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", topic!=\"\"}[10m])) by (topic, service)",
     "legendFormat": "{{topic}} - {{service}}"
    }
   ]
  },
  {
   "title": "Kafka - Topic record consumption - time to catch up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", topic!=\"\"}[10m])) by (topic, service) / sum(avg_over_time(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\", topic!=\"\"}[10m])) by (topic, service)",
     "legendFormat": "{{topic}} - {{service}}"
    }
   ]
  },
  { "title": "StackState Receiver limits", "type": "row", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 } },
  {
   "title": "Receiver - Unique elements seen budget saturation",
   "type": "graph",
   "description": "Percentage of agent element processing budget used, fully saturated when at 1 (i.e. dropping data)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_unique_element_passed_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"} / stackstate_receiver_unique_element_passed_max{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  },
  {
   "title": "Receiver - Created elements hourly budget saturation",
   "type": "graph",
   "description": "Percentage of newly created elements budget used, fully saturated when at 1 (i.e. dropping data)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackstate_receiver_element_create_passed_count{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"} / stackstate_receiver_element_create_passed_max{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", service=~\"$service\"}",
     "legendFormat": "{{element_type}}"
    }
   ]
  }
 ]
}